// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FeatureOnlineStoreAdminService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Request message for
  /// [FeatureOnlineStoreAdminService.CreateFeatureOnlineStore][google.cloud.aiplatform.v1.FeatureOnlineStoreAdminService.CreateFeatureOnlineStore].
  ///
  /// [google.cloud.aiplatform.v1.FeatureOnlineStoreAdminService.CreateFeatureOnlineStore]: <doc:FeatureOnlineStoreAdminServiceClient/createFeatureOnlineStore(request:options:)>
  public struct CreateFeatureOnlineStoreRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the Location to create FeatureOnlineStores.
    /// Format:
    /// `projects/{project}/locations/{location}`
    public var parent: Swift.String = Swift.String()

    /// Required. The FeatureOnlineStore to create.
    public var featureOnlineStore: FeatureOnlineStore? = nil

    /// Required. The ID to use for this FeatureOnlineStore, which will become the
    /// final component of the FeatureOnlineStore's resource name.
    ///
    /// This value may be up to 60 characters, and valid characters are
    /// `[a-z0-9_]`. The first character cannot be a number.
    ///
    /// The value must be unique within the project and location.
    public var featureOnlineStoreId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CreateFeatureOnlineStoreRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateFeatureOnlineStoreRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let parent = CodingKeys(stringValue: "parent")
      static let featureOnlineStore = CodingKeys(stringValue: "featureOnlineStore")
      static let featureOnlineStoreId = CodingKeys(stringValue: "featureOnlineStoreId")

      static let _knownKeys: Set<Swift.String> = [
        "parent",
        "featureOnlineStore",
        "featureOnlineStoreId",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
        self.parent = value
      }
      self.featureOnlineStore = try container.decodeIfPresent(
        FeatureOnlineStore.self, forKey: .featureOnlineStore)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .featureOnlineStoreId)
      {
        self.featureOnlineStoreId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encodeIfPresent(self.featureOnlineStore, forKey: .featureOnlineStore)
      try container.encode(self.featureOnlineStoreId, forKey: .featureOnlineStoreId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `CreateFeatureOnlineStoreRequest`: `"type.googleapis.com/google.cloud.aiplatform.v1.CreateFeatureOnlineStoreRequest"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.CreateFeatureOnlineStoreRequest"
    }

    /// Initialize an instance of `CreateFeatureOnlineStoreRequest` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.CreateFeatureOnlineStoreRequest"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `CreateFeatureOnlineStoreRequest` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
