// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if DatasetService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleCloudLocation
  @_spi(GoogleCloudInternal) public import GoogleIAMV1
  @_spi(GoogleCloudInternal) public import GoogleLongRunning
  @_spi(GoogleCloudInternal) public import GoogleWKT
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// The service that manages Vertex AI Dataset and its child resources.
  ///
  /// @Snippet(path: "DatasetServiceQuickstart")
  public final class DatasetServiceClient: Clients.DatasetServiceProtocol, Sendable {
    let inner: any Clients.DatasetServiceStub
    let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
    let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

    /// Creates a new `DatasetServiceClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.DatasetServiceStub = try Clients.DatasetServiceTransport(options)
      inner = Clients.DatasetServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.DatasetServiceLogging(inner, logger: logger)
      }
      self.inner = inner
      self.pollingErrorPolicy = options.pollingErrorPolicy
      self.pollingBackoffPolicy = options.pollingBackoffPolicy
    }

    /// Creates a Dataset.
    ///
    /// @Snippet(path: "DatasetService_CreateDataset")
    public func createDataset(
      request: CreateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.createDataset(request: request, options: options)
    }

    /// Creates a Dataset.
    ///
    /// @Snippet(path: "DatasetService_CreateDataset")
    public func createDatasetPollingUntilDone(
      request: CreateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> Dataset {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<Dataset>.State in
        return try op._extractStatus(Dataset.self)
      }
      let rawOp = try await self.createDataset(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Dataset>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      return try await poller.wait()
    }

    /// Gets a Dataset.
    ///
    /// @Snippet(path: "DatasetService_GetDataset")
    public func getDataset(
      request: GetDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.Dataset {
      try await self.inner.getDataset(request: request, options: options)
    }

    /// Updates a Dataset.
    ///
    /// @Snippet(path: "DatasetService_UpdateDataset")
    public func updateDataset(
      request: UpdateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.Dataset {
      try await self.inner.updateDataset(request: request, options: options)
    }

    /// Lists Datasets in a Location.
    ///
    /// @Snippet(path: "DatasetService_ListDatasets")
    public func listDatasets(
      request: ListDatasetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListDatasetsResponse {
      try await self.inner.listDatasets(request: request, options: options)
    }

    /// Deletes a Dataset.
    ///
    /// @Snippet(path: "DatasetService_DeleteDataset")
    public func deleteDataset(
      request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.deleteDataset(request: request, options: options)
    }

    /// Deletes a Dataset.
    ///
    /// @Snippet(path: "DatasetService_DeleteDataset")
    public func deleteDatasetPollingUntilDone(
      request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        return try op._extractStatusEmpty()
      }
      let rawOp = try await self.deleteDataset(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      try await poller.wait()
    }

    /// Imports data into a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ImportData")
    public func importData(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.importData(request: request, options: options)
    }

    /// Imports data into a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ImportData")
    public func importDataPollingUntilDone(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> ImportDataResponse {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<ImportDataResponse>.State in
        return try op._extractStatus(ImportDataResponse.self)
      }
      let rawOp = try await self.importData(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<ImportDataResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      return try await poller.wait()
    }

    /// Exports data from a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ExportData")
    public func exportData(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.exportData(request: request, options: options)
    }

    /// Exports data from a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ExportData")
    public func exportDataPollingUntilDone(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> ExportDataResponse {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<ExportDataResponse>.State in
        return try op._extractStatus(ExportDataResponse.self)
      }
      let rawOp = try await self.exportData(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<ExportDataResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      return try await poller.wait()
    }

    /// Create a version from a Dataset.
    ///
    /// @Snippet(path: "DatasetService_CreateDatasetVersion")
    public func createDatasetVersion(
      request: CreateDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.createDatasetVersion(request: request, options: options)
    }

    /// Create a version from a Dataset.
    ///
    /// @Snippet(path: "DatasetService_CreateDatasetVersion")
    public func createDatasetVersionPollingUntilDone(
      request: CreateDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> DatasetVersion {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<DatasetVersion>.State in
        return try op._extractStatus(DatasetVersion.self)
      }
      let rawOp = try await self.createDatasetVersion(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<DatasetVersion>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      return try await poller.wait()
    }

    /// Updates a DatasetVersion.
    ///
    /// @Snippet(path: "DatasetService_UpdateDatasetVersion")
    public func updateDatasetVersion(
      request: UpdateDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.DatasetVersion {
      try await self.inner.updateDatasetVersion(request: request, options: options)
    }

    /// Deletes a Dataset version.
    ///
    /// @Snippet(path: "DatasetService_DeleteDatasetVersion")
    public func deleteDatasetVersion(
      request: DeleteDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.deleteDatasetVersion(request: request, options: options)
    }

    /// Deletes a Dataset version.
    ///
    /// @Snippet(path: "DatasetService_DeleteDatasetVersion")
    public func deleteDatasetVersionPollingUntilDone(
      request: DeleteDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        return try op._extractStatusEmpty()
      }
      let rawOp = try await self.deleteDatasetVersion(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      try await poller.wait()
    }

    /// Gets a Dataset version.
    ///
    /// @Snippet(path: "DatasetService_GetDatasetVersion")
    public func getDatasetVersion(
      request: GetDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.DatasetVersion {
      try await self.inner.getDatasetVersion(request: request, options: options)
    }

    /// Lists DatasetVersions in a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ListDatasetVersions")
    public func listDatasetVersions(
      request: ListDatasetVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListDatasetVersionsResponse {
      try await self.inner.listDatasetVersions(request: request, options: options)
    }

    /// Restores a dataset version.
    ///
    /// @Snippet(path: "DatasetService_RestoreDatasetVersion")
    public func restoreDatasetVersion(
      request: RestoreDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.restoreDatasetVersion(request: request, options: options)
    }

    /// Restores a dataset version.
    ///
    /// @Snippet(path: "DatasetService_RestoreDatasetVersion")
    public func restoreDatasetVersionPollingUntilDone(
      request: RestoreDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> DatasetVersion {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<DatasetVersion>.State in
        return try op._extractStatus(DatasetVersion.self)
      }
      let rawOp = try await self.restoreDatasetVersion(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<DatasetVersion>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      return try await poller.wait()
    }

    /// Lists DataItems in a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ListDataItems")
    public func listDataItems(
      request: ListDataItemsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListDataItemsResponse {
      try await self.inner.listDataItems(request: request, options: options)
    }

    /// Searches DataItems in a Dataset.
    ///
    /// @Snippet(path: "DatasetService_SearchDataItems")
    public func searchDataItems(
      request: SearchDataItemsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.SearchDataItemsResponse {
      try await self.inner.searchDataItems(request: request, options: options)
    }

    /// Lists SavedQueries in a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ListSavedQueries")
    public func listSavedQueries(
      request: ListSavedQueriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListSavedQueriesResponse {
      try await self.inner.listSavedQueries(request: request, options: options)
    }

    /// Deletes a SavedQuery.
    ///
    /// @Snippet(path: "DatasetService_DeleteSavedQuery")
    public func deleteSavedQuery(
      request: DeleteSavedQueryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.deleteSavedQuery(request: request, options: options)
    }

    /// Deletes a SavedQuery.
    ///
    /// @Snippet(path: "DatasetService_DeleteSavedQuery")
    public func deleteSavedQueryPollingUntilDone(
      request: DeleteSavedQueryRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        return try op._extractStatusEmpty()
      }
      let rawOp = try await self.deleteSavedQuery(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      try await poller.wait()
    }

    /// Gets an AnnotationSpec.
    ///
    /// @Snippet(path: "DatasetService_GetAnnotationSpec")
    public func getAnnotationSpec(
      request: GetAnnotationSpecRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.AnnotationSpec {
      try await self.inner.getAnnotationSpec(request: request, options: options)
    }

    /// Lists Annotations belongs to a dataitem.
    ///
    /// @Snippet(path: "DatasetService_ListAnnotations")
    public func listAnnotations(
      request: ListAnnotationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListAnnotationsResponse {
      try await self.inner.listAnnotations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// @Snippet(path: "DatasetService_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "DatasetService_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Sets the access control policy on the specified resource. Replaces
    /// any existing policy.
    ///
    /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
    /// errors.
    ///
    /// @Snippet(path: "DatasetService_SetIamPolicy")
    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self.inner.setIamPolicy(request: request, options: options)
    }

    /// Gets the access control policy for a resource. Returns an empty policy
    /// if the resource exists and does not have a policy set.
    ///
    /// @Snippet(path: "DatasetService_GetIamPolicy")
    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self.inner.getIamPolicy(request: request, options: options)
    }

    /// Returns permissions that a caller has on the specified resource. If the
    /// resource does not exist, this will return an empty set of
    /// permissions, not a `NOT_FOUND` error.
    ///
    /// Note: This operation is designed to be used for building
    /// permission-aware UIs and command-line tools, not for authorization
    /// checking. This operation may "fail open" without warning.
    ///
    /// @Snippet(path: "DatasetService_TestIamPermissions")
    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DatasetService_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DatasetService_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DatasetService_DeleteOperation")
    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DatasetService_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DatasetService_WaitOperation")
    public func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.waitOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `DatasetServiceClient`.
    ///
    /// To mock `DatasetServiceClient` change your functions to receive
    /// `some DatasetServiceProtocol` or `any DatasetServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol DatasetServiceProtocol: Sendable {
      /// See `DatasetServiceClient.createDataset`.
      func createDataset(
        request: CreateDatasetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DatasetServiceClient.createDataset`.
      func createDatasetPollingUntilDone(
        request: CreateDatasetRequest, options: GoogleGax.RequestOptions
      ) async throws -> Dataset

      /// See `DatasetServiceClient.getDataset`.
      func getDataset(
        request: GetDatasetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.Dataset

      /// See `DatasetServiceClient.updateDataset`.
      func updateDataset(
        request: UpdateDatasetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.Dataset

      /// See `DatasetServiceClient.listDatasets`.
      func listDatasets(
        request: ListDatasetsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListDatasetsResponse

      /// See `DatasetServiceClient.deleteDataset`.
      func deleteDataset(
        request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DatasetServiceClient.deleteDataset`.
      func deleteDatasetPollingUntilDone(
        request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `DatasetServiceClient.importData`.
      func importData(
        request: ImportDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DatasetServiceClient.importData`.
      func importDataPollingUntilDone(
        request: ImportDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> ImportDataResponse

      /// See `DatasetServiceClient.exportData`.
      func exportData(
        request: ExportDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DatasetServiceClient.exportData`.
      func exportDataPollingUntilDone(
        request: ExportDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> ExportDataResponse

      /// See `DatasetServiceClient.createDatasetVersion`.
      func createDatasetVersion(
        request: CreateDatasetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DatasetServiceClient.createDatasetVersion`.
      func createDatasetVersionPollingUntilDone(
        request: CreateDatasetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> DatasetVersion

      /// See `DatasetServiceClient.updateDatasetVersion`.
      func updateDatasetVersion(
        request: UpdateDatasetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.DatasetVersion

      /// See `DatasetServiceClient.deleteDatasetVersion`.
      func deleteDatasetVersion(
        request: DeleteDatasetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DatasetServiceClient.deleteDatasetVersion`.
      func deleteDatasetVersionPollingUntilDone(
        request: DeleteDatasetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `DatasetServiceClient.getDatasetVersion`.
      func getDatasetVersion(
        request: GetDatasetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.DatasetVersion

      /// See `DatasetServiceClient.listDatasetVersions`.
      func listDatasetVersions(
        request: ListDatasetVersionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListDatasetVersionsResponse

      /// See `DatasetServiceClient.restoreDatasetVersion`.
      func restoreDatasetVersion(
        request: RestoreDatasetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DatasetServiceClient.restoreDatasetVersion`.
      func restoreDatasetVersionPollingUntilDone(
        request: RestoreDatasetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> DatasetVersion

      /// See `DatasetServiceClient.listDataItems`.
      func listDataItems(
        request: ListDataItemsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListDataItemsResponse

      /// See `DatasetServiceClient.searchDataItems`.
      func searchDataItems(
        request: SearchDataItemsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.SearchDataItemsResponse

      /// See `DatasetServiceClient.listSavedQueries`.
      func listSavedQueries(
        request: ListSavedQueriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListSavedQueriesResponse

      /// See `DatasetServiceClient.deleteSavedQuery`.
      func deleteSavedQuery(
        request: DeleteSavedQueryRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DatasetServiceClient.deleteSavedQuery`.
      func deleteSavedQueryPollingUntilDone(
        request: DeleteSavedQueryRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `DatasetServiceClient.getAnnotationSpec`.
      func getAnnotationSpec(
        request: GetAnnotationSpecRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.AnnotationSpec

      /// See `DatasetServiceClient.listAnnotations`.
      func listAnnotations(
        request: ListAnnotationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListAnnotationsResponse

      /// See `DatasetServiceClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `DatasetServiceClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `DatasetServiceClient.setIamPolicy`.
      func setIamPolicy(
        request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      /// See `DatasetServiceClient.getIamPolicy`.
      func getIamPolicy(
        request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      /// See `DatasetServiceClient.testIamPermissions`.
      func testIamPermissions(
        request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

      /// See `DatasetServiceClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `DatasetServiceClient.deleteOperation`.
      func deleteOperation(
        request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `DatasetServiceClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `DatasetServiceClient.waitOperation`.
      func waitOperation(
        request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation
    }
  }

  // Default implementations
  extension Clients.DatasetServiceProtocol {
    public func createDataset(request: CreateDatasetRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.createDataset(request: request, options: .init())
    }

    public func createDataset(
      request: CreateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createDatasetPollingUntilDone(request: CreateDatasetRequest) async throws -> Dataset
    {
      return try await self.createDatasetPollingUntilDone(request: request, options: .init())
    }

    public func createDatasetPollingUntilDone(
      request: CreateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> Dataset {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createDatasetPollingUntilDone(
      parent: Swift.String,
      dataset: Dataset?,
    ) async throws -> Dataset {
      let request = CreateDatasetRequest().with {
        $0.parent = parent
        $0.dataset = dataset
      }
      return try await self.createDatasetPollingUntilDone(request: request)
    }

    public func getDataset(request: GetDatasetRequest) async throws
      -> GoogleCloudAIPlatformV1.Dataset
    {
      try await self.getDataset(request: request, options: .init())
    }

    public func getDataset(
      request: GetDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.Dataset {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getDataset(
      name: Swift.String,
    ) async throws -> GoogleCloudAIPlatformV1.Dataset {
      let request = GetDatasetRequest().with {
        $0.name = name
      }
      return try await self.getDataset(request: request)
    }

    public func updateDataset(request: UpdateDatasetRequest) async throws
      -> GoogleCloudAIPlatformV1.Dataset
    {
      try await self.updateDataset(request: request, options: .init())
    }

    public func updateDataset(
      request: UpdateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.Dataset {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateDataset(
      dataset: Dataset?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> GoogleCloudAIPlatformV1.Dataset {
      let request = UpdateDatasetRequest().with {
        $0.dataset = dataset
        $0.updateMask = updateMask
      }
      return try await self.updateDataset(request: request)
    }

    public func listDatasets(request: ListDatasetsRequest) async throws
      -> GoogleCloudAIPlatformV1.ListDatasetsResponse
    {
      try await self.listDatasets(request: request, options: .init())
    }

    public func listDatasets(
      request: ListDatasetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListDatasetsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listDatasetsByItems(
      request: ListDatasetsRequest
    ) -> some AsyncSequence<Dataset, Swift.Error> & Sendable {
      self.listDatasetsByItems(request: request, options: .init())
    }

    /// Lists Datasets in a Location.
    ///
    /// @Snippet(path: "DatasetService_ListDatasets")
    public func listDatasetsByItems(
      request: ListDatasetsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<Dataset, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudAIPlatformV1.ListDatasetsResponse
        in
        var request = request
        request.pageToken = token
        return try await self.listDatasets(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listDatasetsByItems(
      parent: Swift.String,
    ) -> some AsyncSequence<Dataset, Swift.Error> & Sendable {
      let request = ListDatasetsRequest().with {
        $0.parent = parent
      }
      return self.listDatasetsByItems(request: request)
    }

    public func deleteDataset(request: DeleteDatasetRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.deleteDataset(request: request, options: .init())
    }

    public func deleteDataset(
      request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteDatasetPollingUntilDone(request: DeleteDatasetRequest) async throws {
      try await self.deleteDatasetPollingUntilDone(request: request, options: .init())
    }

    public func deleteDatasetPollingUntilDone(
      request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteDatasetPollingUntilDone(
      name: Swift.String,
    ) async throws {
      let request = DeleteDatasetRequest().with {
        $0.name = name
      }
      try await self.deleteDatasetPollingUntilDone(request: request)
    }

    public func importData(request: ImportDataRequest) async throws -> GoogleLongRunning.Operation {
      try await self.importData(request: request, options: .init())
    }

    public func importData(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func importDataPollingUntilDone(request: ImportDataRequest) async throws
      -> ImportDataResponse
    {
      return try await self.importDataPollingUntilDone(request: request, options: .init())
    }

    public func importDataPollingUntilDone(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> ImportDataResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func importDataPollingUntilDone(
      name: Swift.String,
      importConfigs: [ImportDataConfig],
    ) async throws -> ImportDataResponse {
      let request = ImportDataRequest().with {
        $0.name = name
        $0.importConfigs = importConfigs
      }
      return try await self.importDataPollingUntilDone(request: request)
    }

    public func exportData(request: ExportDataRequest) async throws -> GoogleLongRunning.Operation {
      try await self.exportData(request: request, options: .init())
    }

    public func exportData(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func exportDataPollingUntilDone(request: ExportDataRequest) async throws
      -> ExportDataResponse
    {
      return try await self.exportDataPollingUntilDone(request: request, options: .init())
    }

    public func exportDataPollingUntilDone(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> ExportDataResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func exportDataPollingUntilDone(
      name: Swift.String,
      exportConfig: ExportDataConfig?,
    ) async throws -> ExportDataResponse {
      let request = ExportDataRequest().with {
        $0.name = name
        $0.exportConfig = exportConfig
      }
      return try await self.exportDataPollingUntilDone(request: request)
    }

    public func createDatasetVersion(request: CreateDatasetVersionRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.createDatasetVersion(request: request, options: .init())
    }

    public func createDatasetVersion(
      request: CreateDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createDatasetVersionPollingUntilDone(request: CreateDatasetVersionRequest)
      async throws -> DatasetVersion
    {
      return try await self.createDatasetVersionPollingUntilDone(request: request, options: .init())
    }

    public func createDatasetVersionPollingUntilDone(
      request: CreateDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> DatasetVersion {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createDatasetVersionPollingUntilDone(
      parent: Swift.String,
      datasetVersion: DatasetVersion?,
    ) async throws -> DatasetVersion {
      let request = CreateDatasetVersionRequest().with {
        $0.parent = parent
        $0.datasetVersion = datasetVersion
      }
      return try await self.createDatasetVersionPollingUntilDone(request: request)
    }

    public func updateDatasetVersion(request: UpdateDatasetVersionRequest) async throws
      -> GoogleCloudAIPlatformV1.DatasetVersion
    {
      try await self.updateDatasetVersion(request: request, options: .init())
    }

    public func updateDatasetVersion(
      request: UpdateDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.DatasetVersion {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateDatasetVersion(
      datasetVersion: DatasetVersion?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> GoogleCloudAIPlatformV1.DatasetVersion {
      let request = UpdateDatasetVersionRequest().with {
        $0.datasetVersion = datasetVersion
        $0.updateMask = updateMask
      }
      return try await self.updateDatasetVersion(request: request)
    }

    public func deleteDatasetVersion(request: DeleteDatasetVersionRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.deleteDatasetVersion(request: request, options: .init())
    }

    public func deleteDatasetVersion(
      request: DeleteDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteDatasetVersionPollingUntilDone(request: DeleteDatasetVersionRequest)
      async throws
    {
      try await self.deleteDatasetVersionPollingUntilDone(request: request, options: .init())
    }

    public func deleteDatasetVersionPollingUntilDone(
      request: DeleteDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteDatasetVersionPollingUntilDone(
      name: Swift.String,
    ) async throws {
      let request = DeleteDatasetVersionRequest().with {
        $0.name = name
      }
      try await self.deleteDatasetVersionPollingUntilDone(request: request)
    }

    public func getDatasetVersion(request: GetDatasetVersionRequest) async throws
      -> GoogleCloudAIPlatformV1.DatasetVersion
    {
      try await self.getDatasetVersion(request: request, options: .init())
    }

    public func getDatasetVersion(
      request: GetDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.DatasetVersion {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getDatasetVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudAIPlatformV1.DatasetVersion {
      let request = GetDatasetVersionRequest().with {
        $0.name = name
      }
      return try await self.getDatasetVersion(request: request)
    }

    public func listDatasetVersions(request: ListDatasetVersionsRequest) async throws
      -> GoogleCloudAIPlatformV1.ListDatasetVersionsResponse
    {
      try await self.listDatasetVersions(request: request, options: .init())
    }

    public func listDatasetVersions(
      request: ListDatasetVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListDatasetVersionsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listDatasetVersionsByItems(
      request: ListDatasetVersionsRequest
    ) -> some AsyncSequence<DatasetVersion, Swift.Error> & Sendable {
      self.listDatasetVersionsByItems(request: request, options: .init())
    }

    /// Lists DatasetVersions in a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ListDatasetVersions")
    public func listDatasetVersionsByItems(
      request: ListDatasetVersionsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<DatasetVersion, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudAIPlatformV1.ListDatasetVersionsResponse in
        var request = request
        request.pageToken = token
        return try await self.listDatasetVersions(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listDatasetVersionsByItems(
      parent: Swift.String,
    ) -> some AsyncSequence<DatasetVersion, Swift.Error> & Sendable {
      let request = ListDatasetVersionsRequest().with {
        $0.parent = parent
      }
      return self.listDatasetVersionsByItems(request: request)
    }

    public func restoreDatasetVersion(request: RestoreDatasetVersionRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.restoreDatasetVersion(request: request, options: .init())
    }

    public func restoreDatasetVersion(
      request: RestoreDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func restoreDatasetVersionPollingUntilDone(request: RestoreDatasetVersionRequest)
      async throws -> DatasetVersion
    {
      return try await self.restoreDatasetVersionPollingUntilDone(
        request: request, options: .init())
    }

    public func restoreDatasetVersionPollingUntilDone(
      request: RestoreDatasetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> DatasetVersion {
      throw GoogleGax.RequestError.unimplemented
    }

    public func restoreDatasetVersionPollingUntilDone(
      name: Swift.String,
    ) async throws -> DatasetVersion {
      let request = RestoreDatasetVersionRequest().with {
        $0.name = name
      }
      return try await self.restoreDatasetVersionPollingUntilDone(request: request)
    }

    public func listDataItems(request: ListDataItemsRequest) async throws
      -> GoogleCloudAIPlatformV1.ListDataItemsResponse
    {
      try await self.listDataItems(request: request, options: .init())
    }

    public func listDataItems(
      request: ListDataItemsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListDataItemsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listDataItemsByItems(
      request: ListDataItemsRequest
    ) -> some AsyncSequence<DataItem, Swift.Error> & Sendable {
      self.listDataItemsByItems(request: request, options: .init())
    }

    /// Lists DataItems in a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ListDataItems")
    public func listDataItemsByItems(
      request: ListDataItemsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<DataItem, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudAIPlatformV1.ListDataItemsResponse in
        var request = request
        request.pageToken = token
        return try await self.listDataItems(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listDataItemsByItems(
      parent: Swift.String,
    ) -> some AsyncSequence<DataItem, Swift.Error> & Sendable {
      let request = ListDataItemsRequest().with {
        $0.parent = parent
      }
      return self.listDataItemsByItems(request: request)
    }

    public func searchDataItems(request: SearchDataItemsRequest) async throws
      -> GoogleCloudAIPlatformV1.SearchDataItemsResponse
    {
      try await self.searchDataItems(request: request, options: .init())
    }

    public func searchDataItems(
      request: SearchDataItemsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.SearchDataItemsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func searchDataItemsByItems(
      request: SearchDataItemsRequest
    ) -> some AsyncSequence<DataItemView, Swift.Error> & Sendable {
      self.searchDataItemsByItems(request: request, options: .init())
    }

    /// Searches DataItems in a Dataset.
    ///
    /// @Snippet(path: "DatasetService_SearchDataItems")
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func searchDataItemsByItems(
      request: SearchDataItemsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<DataItemView, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudAIPlatformV1.SearchDataItemsResponse in
        var request = request
        request.pageToken = token
        return try await self.searchDataItems(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listSavedQueries(request: ListSavedQueriesRequest) async throws
      -> GoogleCloudAIPlatformV1.ListSavedQueriesResponse
    {
      try await self.listSavedQueries(request: request, options: .init())
    }

    public func listSavedQueries(
      request: ListSavedQueriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListSavedQueriesResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listSavedQueriesByItems(
      request: ListSavedQueriesRequest
    ) -> some AsyncSequence<SavedQuery, Swift.Error> & Sendable {
      self.listSavedQueriesByItems(request: request, options: .init())
    }

    /// Lists SavedQueries in a Dataset.
    ///
    /// @Snippet(path: "DatasetService_ListSavedQueries")
    public func listSavedQueriesByItems(
      request: ListSavedQueriesRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<SavedQuery, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudAIPlatformV1.ListSavedQueriesResponse in
        var request = request
        request.pageToken = token
        return try await self.listSavedQueries(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listSavedQueriesByItems(
      parent: Swift.String,
    ) -> some AsyncSequence<SavedQuery, Swift.Error> & Sendable {
      let request = ListSavedQueriesRequest().with {
        $0.parent = parent
      }
      return self.listSavedQueriesByItems(request: request)
    }

    public func deleteSavedQuery(request: DeleteSavedQueryRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.deleteSavedQuery(request: request, options: .init())
    }

    public func deleteSavedQuery(
      request: DeleteSavedQueryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteSavedQueryPollingUntilDone(request: DeleteSavedQueryRequest) async throws {
      try await self.deleteSavedQueryPollingUntilDone(request: request, options: .init())
    }

    public func deleteSavedQueryPollingUntilDone(
      request: DeleteSavedQueryRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteSavedQueryPollingUntilDone(
      name: Swift.String,
    ) async throws {
      let request = DeleteSavedQueryRequest().with {
        $0.name = name
      }
      try await self.deleteSavedQueryPollingUntilDone(request: request)
    }

    public func getAnnotationSpec(request: GetAnnotationSpecRequest) async throws
      -> GoogleCloudAIPlatformV1.AnnotationSpec
    {
      try await self.getAnnotationSpec(request: request, options: .init())
    }

    public func getAnnotationSpec(
      request: GetAnnotationSpecRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.AnnotationSpec {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getAnnotationSpec(
      name: Swift.String,
    ) async throws -> GoogleCloudAIPlatformV1.AnnotationSpec {
      let request = GetAnnotationSpecRequest().with {
        $0.name = name
      }
      return try await self.getAnnotationSpec(request: request)
    }

    public func listAnnotations(request: ListAnnotationsRequest) async throws
      -> GoogleCloudAIPlatformV1.ListAnnotationsResponse
    {
      try await self.listAnnotations(request: request, options: .init())
    }

    public func listAnnotations(
      request: ListAnnotationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListAnnotationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listAnnotationsByItems(
      request: ListAnnotationsRequest
    ) -> some AsyncSequence<GoogleCloudAIPlatformV1.Annotation, Swift.Error> & Sendable {
      self.listAnnotationsByItems(request: request, options: .init())
    }

    /// Lists Annotations belongs to a dataitem.
    ///
    /// @Snippet(path: "DatasetService_ListAnnotations")
    public func listAnnotationsByItems(
      request: ListAnnotationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleCloudAIPlatformV1.Annotation, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudAIPlatformV1.ListAnnotationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listAnnotations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listAnnotationsByItems(
      parent: Swift.String,
    ) -> some AsyncSequence<GoogleCloudAIPlatformV1.Annotation, Swift.Error> & Sendable {
      let request = ListAnnotationsRequest().with {
        $0.parent = parent
      }
      return self.listAnnotationsByItems(request: request)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest
    ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
      self.listLocationsByItems(request: request, options: .init())
    }

    /// Lists information about the supported locations for this service.
    ///
    /// @Snippet(path: "DatasetService_ListLocations")
    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
      -> GoogleIAMV1.Policy
    {
      try await self.setIamPolicy(request: request, options: .init())
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
      -> GoogleIAMV1.Policy
    {
      try await self.getIamPolicy(request: request, options: .init())
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse
    {
      try await self.testIamPermissions(request: request, options: .init())
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      self.listOperationsByItems(request: request, options: .init())
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DatasetService_ListOperations")
    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listOperationsByItems(
      name: Swift.String,
      filter: Swift.String,
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return self.listOperationsByItems(request: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
      try await self.deleteOperation(request: request, options: .init())
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.DeleteOperationRequest().with {
        $0.name = name
      }
      try await self.deleteOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }

    public func waitOperation(request: GoogleLongRunning.WaitOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.waitOperation(request: request, options: .init())
    }

    public func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'DatasetService' trait in Package.swift to use this client."
  )
  public final class DatasetServiceClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'DatasetService' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
