// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if DeploymentResourcePoolService || EndpointService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// A deployment of a Model. Endpoints contain one or more DeployedModels.
  public struct DeployedModel: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Immutable. The ID of the DeployedModel. If not provided upon deployment,
    /// Vertex AI will generate a value for this ID.
    ///
    /// This value should be 1-10 characters, and valid characters are `/[0-9]/`.
    public var id: Swift.String = Swift.String()

    /// The resource name of the Model that this is the deployment of. Note that
    /// the Model may be in a different location than the DeployedModel's Endpoint.
    ///
    /// The resource name may contain version id or version alias to specify the
    /// version.
    ///  Example: `projects/{project}/locations/{location}/models/{model}@2`
    ///              or
    ///            `projects/{project}/locations/{location}/models/{model}@golden`
    /// if no version is specified, the default version will be deployed.
    public var model: Swift.String = Swift.String()

    /// Output only. The version ID of the model that is deployed.
    public var modelVersionId: Swift.String = Swift.String()

    /// The display name of the DeployedModel. If not provided upon creation,
    /// the Model's display_name is used.
    public var displayName: Swift.String = Swift.String()

    /// Output only. Timestamp when the DeployedModel was created.
    public var createTime: GoogleWKT.WKTTimestamp? = nil

    /// Explanation configuration for this DeployedModel.
    ///
    /// When deploying a Model using
    /// [EndpointService.DeployModel][google.cloud.aiplatform.v1.EndpointService.DeployModel],
    /// this value overrides the value of
    /// [Model.explanation_spec][google.cloud.aiplatform.v1.Model.explanation_spec].
    /// All fields of
    /// [explanation_spec][google.cloud.aiplatform.v1.DeployedModel.explanation_spec]
    /// are optional in the request. If a field of
    /// [explanation_spec][google.cloud.aiplatform.v1.DeployedModel.explanation_spec]
    /// is not populated, the value of the same field of
    /// [Model.explanation_spec][google.cloud.aiplatform.v1.Model.explanation_spec]
    /// is inherited. If the corresponding
    /// [Model.explanation_spec][google.cloud.aiplatform.v1.Model.explanation_spec]
    /// is not populated, all fields of the
    /// [explanation_spec][google.cloud.aiplatform.v1.DeployedModel.explanation_spec]
    /// will be used for the explanation configuration.
    ///
    /// [google.cloud.aiplatform.v1.DeployedModel.explanation_spec]: <doc:DeployedModel/explanationSpec>
    /// [google.cloud.aiplatform.v1.EndpointService.DeployModel]: <doc:EndpointServiceClient/deployModel(request:options:)>
    /// [google.cloud.aiplatform.v1.Model.explanation_spec]: <doc:Model/explanationSpec>
    public var explanationSpec: ExplanationSpec? = nil

    /// If true, deploy the model without explainable feature, regardless the
    /// existence of
    /// [Model.explanation_spec][google.cloud.aiplatform.v1.Model.explanation_spec]
    /// or
    /// [explanation_spec][google.cloud.aiplatform.v1.DeployedModel.explanation_spec].
    ///
    /// [google.cloud.aiplatform.v1.DeployedModel.explanation_spec]: <doc:DeployedModel/explanationSpec>
    /// [google.cloud.aiplatform.v1.Model.explanation_spec]: <doc:Model/explanationSpec>
    public var disableExplanations: Swift.Bool = Swift.Bool()

    /// The service account that the DeployedModel's container runs as. Specify the
    /// email address of the service account. If this service account is not
    /// specified, the container runs as a service account that doesn't have access
    /// to the resource project.
    ///
    /// Users deploying the Model must have the `iam.serviceAccounts.actAs`
    /// permission on this service account.
    public var serviceAccount: Swift.String = Swift.String()

    /// For custom-trained Models and AutoML Tabular Models, the container of the
    /// DeployedModel instances will send `stderr` and `stdout` streams to
    /// Cloud Logging by default. Please note that the logs incur cost,
    /// which are subject to [Cloud Logging
    /// pricing](https://cloud.google.com/logging/pricing).
    ///
    /// User can disable container logging by setting this flag to true.
    public var disableContainerLogging: Swift.Bool = Swift.Bool()

    /// If true, online prediction access logs are sent to Cloud
    /// Logging.
    /// These logs are like standard server access logs, containing
    /// information like timestamp and latency for each prediction request.
    ///
    /// Note that logs may incur a cost, especially if your project
    /// receives prediction requests at a high queries per second rate (QPS).
    /// Estimate your costs before enabling this option.
    public var enableAccessLogging: Swift.Bool = Swift.Bool()

    /// Output only. Provide paths for users to send predict/explain/health
    /// requests directly to the deployed model services running on Cloud via
    /// private services access. This field is populated if
    /// [network][google.cloud.aiplatform.v1.Endpoint.network] is configured.
    ///
    /// [google.cloud.aiplatform.v1.Endpoint.network]: <doc:Endpoint/network>
    public var privateEndpoints: PrivateEndpoints? = nil

    /// Configuration for faster model deployment.
    public var fasterDeploymentConfig: FasterDeploymentConfig? = nil

    /// Output only. Runtime status of the deployed model.
    public var status: DeployedModel.Status? = nil

    /// System labels to apply to Model Garden deployments.
    /// System labels are managed by Google for internal use only.
    public var systemLabels: [Swift.String: Swift.String] = [:]

    /// The checkpoint id of the model.
    public var checkpointId: Swift.String = Swift.String()

    /// Optional. Spec for configuring speculative decoding.
    public var speculativeDecodingSpec: SpeculativeDecodingSpec? = nil

    /// The prediction (for example, the machine) resources that the DeployedModel
    /// uses. The user is billed for the resources (at least their minimal amount)
    /// even if the DeployedModel receives no traffic.
    /// Not all Models support all resources types. See
    /// [Model.supported_deployment_resources_types][google.cloud.aiplatform.v1.Model.supported_deployment_resources_types].
    /// Required except for Large Model Deploy use cases.
    ///
    /// [google.cloud.aiplatform.v1.Model.supported_deployment_resources_types]: <doc:Model/supportedDeploymentResourcesTypes>
    public var predictionResources: PredictionResourcesOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DeployedModel`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeployedModel().with { $0.dedicatedResources = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dedicatedResources = CodingKeys(stringValue: "dedicatedResources")
      static let automaticResources = CodingKeys(stringValue: "automaticResources")
      static let sharedResources = CodingKeys(stringValue: "sharedResources")
      static let id = CodingKeys(stringValue: "id")
      static let model = CodingKeys(stringValue: "model")
      static let modelVersionId = CodingKeys(stringValue: "modelVersionId")
      static let displayName = CodingKeys(stringValue: "displayName")
      static let createTime = CodingKeys(stringValue: "createTime")
      static let explanationSpec = CodingKeys(stringValue: "explanationSpec")
      static let disableExplanations = CodingKeys(stringValue: "disableExplanations")
      static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
      static let disableContainerLogging = CodingKeys(stringValue: "disableContainerLogging")
      static let enableAccessLogging = CodingKeys(stringValue: "enableAccessLogging")
      static let privateEndpoints = CodingKeys(stringValue: "privateEndpoints")
      static let fasterDeploymentConfig = CodingKeys(stringValue: "fasterDeploymentConfig")
      static let status = CodingKeys(stringValue: "status")
      static let systemLabels = CodingKeys(stringValue: "systemLabels")
      static let checkpointId = CodingKeys(stringValue: "checkpointId")
      static let speculativeDecodingSpec = CodingKeys(stringValue: "speculativeDecodingSpec")

      static let _knownKeys: Set<Swift.String> = [
        "dedicatedResources",
        "automaticResources",
        "sharedResources",
        "id",
        "model",
        "modelVersionId",
        "displayName",
        "createTime",
        "explanationSpec",
        "disableExplanations",
        "serviceAccount",
        "disableContainerLogging",
        "enableAccessLogging",
        "privateEndpoints",
        "fasterDeploymentConfig",
        "status",
        "systemLabels",
        "checkpointId",
        "speculativeDecodingSpec",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
        self.model = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .modelVersionId) {
        self.modelVersionId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      self.createTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .createTime)
      self.explanationSpec = try container.decodeIfPresent(
        ExplanationSpec.self, forKey: .explanationSpec)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disableExplanations) {
        self.disableExplanations = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
        self.serviceAccount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .disableContainerLogging)
      {
        self.disableContainerLogging = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableAccessLogging) {
        self.enableAccessLogging = value
      }
      self.privateEndpoints = try container.decodeIfPresent(
        PrivateEndpoints.self, forKey: .privateEndpoints)
      self.fasterDeploymentConfig = try container.decodeIfPresent(
        FasterDeploymentConfig.self, forKey: .fasterDeploymentConfig)
      self.status = try container.decodeIfPresent(DeployedModel.Status.self, forKey: .status)
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .systemLabels)
      {
        self.systemLabels = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .checkpointId) {
        self.checkpointId = value
      }
      self.speculativeDecodingSpec = try container.decodeIfPresent(
        SpeculativeDecodingSpec.self, forKey: .speculativeDecodingSpec)

      var predictionResources: PredictionResourcesOneOf? = nil
      let predictionResourcesCheckAndSet = {
        if predictionResources != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'predictionResources'"))
        }
        predictionResources = $0
      }
      if let dedicatedResources = try container.decodeIfPresent(
        DedicatedResources.self, forKey: .dedicatedResources)
      {
        try predictionResourcesCheckAndSet(.dedicatedResources(dedicatedResources))
      }
      if let automaticResources = try container.decodeIfPresent(
        AutomaticResources.self, forKey: .automaticResources)
      {
        try predictionResourcesCheckAndSet(.automaticResources(automaticResources))
      }
      if let sharedResources = try container.decodeIfPresent(
        Swift.String.self, forKey: .sharedResources)
      {
        try predictionResourcesCheckAndSet(.sharedResources(sharedResources))
      }
      self.predictionResources = predictionResources
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.model, forKey: .model)
      try container.encode(self.modelVersionId, forKey: .modelVersionId)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encodeIfPresent(self.createTime, forKey: .createTime)
      try container.encodeIfPresent(self.explanationSpec, forKey: .explanationSpec)
      try container.encode(self.disableExplanations, forKey: .disableExplanations)
      try container.encode(self.serviceAccount, forKey: .serviceAccount)
      try container.encode(self.disableContainerLogging, forKey: .disableContainerLogging)
      try container.encode(self.enableAccessLogging, forKey: .enableAccessLogging)
      try container.encodeIfPresent(self.privateEndpoints, forKey: .privateEndpoints)
      try container.encodeIfPresent(self.fasterDeploymentConfig, forKey: .fasterDeploymentConfig)
      try container.encodeIfPresent(self.status, forKey: .status)
      try container.encode(self.systemLabels, forKey: .systemLabels)
      try container.encode(self.checkpointId, forKey: .checkpointId)
      try container.encodeIfPresent(self.speculativeDecodingSpec, forKey: .speculativeDecodingSpec)

      if let choice = self.predictionResources {
        switch choice {
        case .dedicatedResources(let value):
          try container.encode(value, forKey: .dedicatedResources)
        case .automaticResources(let value):
          try container.encode(value, forKey: .automaticResources)
        case .sharedResources(let value):
          try container.encode(value, forKey: .sharedResources)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Runtime status of the deployed model.
    public struct Status: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Output only. The latest deployed model's status message (if any).
      public var message: Swift.String = Swift.String()

      /// Output only. The time at which the status was last updated.
      public var lastUpdateTime: GoogleWKT.WKTTimestamp? = nil

      /// Output only. The number of available replicas of the deployed model.
      public var availableReplicaCount: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Status`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Status().with { $0.message = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let message = CodingKeys(stringValue: "message")
        static let lastUpdateTime = CodingKeys(stringValue: "lastUpdateTime")
        static let availableReplicaCount = CodingKeys(stringValue: "availableReplicaCount")

        static let _knownKeys: Set<Swift.String> = [
          "message",
          "lastUpdateTime",
          "availableReplicaCount",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
          self.message = value
        }
        self.lastUpdateTime = try container.decodeIfPresent(
          GoogleWKT.WKTTimestamp.self, forKey: .lastUpdateTime)
        if let value = try container.decodeIfPresent(
          Swift.Int32.self, forKey: .availableReplicaCount)
        {
          self.availableReplicaCount = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.message, forKey: .message)
        try container.encodeIfPresent(self.lastUpdateTime, forKey: .lastUpdateTime)
        try container.encode(self.availableReplicaCount, forKey: .availableReplicaCount)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.DeployedModel.Status"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The prediction (for example, the machine) resources that the DeployedModel
    /// uses. The user is billed for the resources (at least their minimal amount)
    /// even if the DeployedModel receives no traffic.
    /// Not all Models support all resources types. See
    /// [Model.supported_deployment_resources_types][google.cloud.aiplatform.v1.Model.supported_deployment_resources_types].
    /// Required except for Large Model Deploy use cases.
    ///
    /// [google.cloud.aiplatform.v1.Model.supported_deployment_resources_types]: <doc:Model/supportedDeploymentResourcesTypes>
    public enum PredictionResourcesOneOf: Codable, Equatable, Sendable {
      /// A description of resources that are dedicated to the DeployedModel, and
      /// that need a higher degree of manual configuration.
      indirect case dedicatedResources(DedicatedResources)
      /// A description of resources that to large degree are decided by Vertex
      /// AI, and require only a modest additional configuration.
      indirect case automaticResources(AutomaticResources)
      /// The resource name of the shared DeploymentResourcePool to deploy on.
      /// Format:
      /// `projects/{project}/locations/{location}/deploymentResourcePools/{deployment_resource_pool}`
      case sharedResources(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.DeployedModel"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
