// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GenAiTuningService
  import Foundation
  public import GoogleRpc
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Evaluate Dataset Run Result for Tuning Job.
  public struct EvaluateDatasetRun: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Deprecated: The updated architecture uses evaluation_run
    /// instead.
    @available(*, deprecated)
    public var operationName: Swift.String = Swift.String()

    /// Output only. The resource name of the evaluation run. Format:
    /// `projects/{project}/locations/{location}/evaluationRuns/{evaluation_run_id}`.
    public var evaluationRun: Swift.String = Swift.String()

    /// Output only. The checkpoint id used in the evaluation run. Only populated
    /// when evaluating checkpoints.
    public var checkpointId: Swift.String = Swift.String()

    /// Output only. Results for EvaluationService.
    public var evaluateDatasetResponse: EvaluateDatasetResponse? = nil

    /// Output only. The error of the evaluation run if any.
    public var error: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EvaluateDatasetRun`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EvaluateDatasetRun().with { $0.operationName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let operationName = CodingKeys(stringValue: "operationName")
      static let evaluationRun = CodingKeys(stringValue: "evaluationRun")
      static let checkpointId = CodingKeys(stringValue: "checkpointId")
      static let evaluateDatasetResponse = CodingKeys(stringValue: "evaluateDatasetResponse")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "operationName",
        "evaluationRun",
        "checkpointId",
        "evaluateDatasetResponse",
        "error",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationName) {
        self.operationName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .evaluationRun) {
        self.evaluationRun = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .checkpointId) {
        self.checkpointId = value
      }
      self.evaluateDatasetResponse = try container.decodeIfPresent(
        EvaluateDatasetResponse.self, forKey: .evaluateDatasetResponse)
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.operationName, forKey: .operationName)
      try container.encode(self.evaluationRun, forKey: .evaluationRun)
      try container.encode(self.checkpointId, forKey: .checkpointId)
      try container.encodeIfPresent(self.evaluateDatasetResponse, forKey: .evaluateDatasetResponse)
      try container.encodeIfPresent(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `EvaluateDatasetRun`: `"type.googleapis.com/google.cloud.aiplatform.v1.EvaluateDatasetRun"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.EvaluateDatasetRun"
    }

    /// Initialize an instance of `EvaluateDatasetRun` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.EvaluateDatasetRun"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `EvaluateDatasetRun` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
