// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FeaturestoreService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Configuration of how features in Featurestore are monitored.
  public struct FeaturestoreMonitoringConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The config for Snapshot Analysis Based Feature Monitoring.
    public var snapshotAnalysis: FeaturestoreMonitoringConfig.SnapshotAnalysis? = nil

    /// The config for ImportFeatures Analysis Based Feature Monitoring.
    public var importFeaturesAnalysis: FeaturestoreMonitoringConfig.ImportFeaturesAnalysis? = nil

    /// Threshold for numerical features of anomaly detection.
    /// This is shared by all objectives of Featurestore Monitoring for numerical
    /// features (i.e. Features with type
    /// ([Feature.ValueType][google.cloud.aiplatform.v1.Feature.ValueType]) DOUBLE
    /// or INT64).
    ///
    /// [google.cloud.aiplatform.v1.Feature.ValueType]: <doc:Feature/ValueType>
    public var numericalThresholdConfig: FeaturestoreMonitoringConfig.ThresholdConfig? = nil

    /// Threshold for categorical features of anomaly detection.
    /// This is shared by all types of Featurestore Monitoring for categorical
    /// features (i.e. Features with type
    /// ([Feature.ValueType][google.cloud.aiplatform.v1.Feature.ValueType]) BOOL or
    /// STRING).
    ///
    /// [google.cloud.aiplatform.v1.Feature.ValueType]: <doc:Feature/ValueType>
    public var categoricalThresholdConfig: FeaturestoreMonitoringConfig.ThresholdConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FeaturestoreMonitoringConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FeaturestoreMonitoringConfig().with { $0.snapshotAnalysis = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let snapshotAnalysis = CodingKeys(stringValue: "snapshotAnalysis")
      static let importFeaturesAnalysis = CodingKeys(stringValue: "importFeaturesAnalysis")
      static let numericalThresholdConfig = CodingKeys(stringValue: "numericalThresholdConfig")
      static let categoricalThresholdConfig = CodingKeys(stringValue: "categoricalThresholdConfig")

      static let _knownKeys: Set<Swift.String> = [
        "snapshotAnalysis",
        "importFeaturesAnalysis",
        "numericalThresholdConfig",
        "categoricalThresholdConfig",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.snapshotAnalysis = try container.decodeIfPresent(
        FeaturestoreMonitoringConfig.SnapshotAnalysis.self, forKey: .snapshotAnalysis)
      self.importFeaturesAnalysis = try container.decodeIfPresent(
        FeaturestoreMonitoringConfig.ImportFeaturesAnalysis.self, forKey: .importFeaturesAnalysis)
      self.numericalThresholdConfig = try container.decodeIfPresent(
        FeaturestoreMonitoringConfig.ThresholdConfig.self, forKey: .numericalThresholdConfig)
      self.categoricalThresholdConfig = try container.decodeIfPresent(
        FeaturestoreMonitoringConfig.ThresholdConfig.self, forKey: .categoricalThresholdConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.snapshotAnalysis, forKey: .snapshotAnalysis)
      try container.encodeIfPresent(self.importFeaturesAnalysis, forKey: .importFeaturesAnalysis)
      try container.encodeIfPresent(
        self.numericalThresholdConfig, forKey: .numericalThresholdConfig)
      try container.encodeIfPresent(
        self.categoricalThresholdConfig, forKey: .categoricalThresholdConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Configuration of the Featurestore's Snapshot Analysis Based Monitoring.
    /// This type of analysis generates statistics for each Feature based on a
    /// snapshot of the latest feature value of each entities every
    /// monitoring_interval.
    public struct SnapshotAnalysis: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The monitoring schedule for snapshot analysis.
      /// For EntityType-level config:
      ///   unset / disabled = true indicates disabled by
      ///   default for Features under it; otherwise by default enable snapshot
      ///   analysis monitoring with monitoring_interval for Features under it.
      /// Feature-level config:
      ///   disabled = true indicates disabled regardless of the EntityType-level
      ///   config; unset monitoring_interval indicates going with EntityType-level
      ///   config; otherwise run snapshot analysis monitoring with
      ///   monitoring_interval regardless of the EntityType-level config.
      /// Explicitly Disable the snapshot analysis based monitoring.
      public var disabled: Swift.Bool = Swift.Bool()

      /// Configuration of the snapshot analysis based monitoring pipeline
      /// running interval. The value indicates number of days.
      public var monitoringIntervalDays: Swift.Int32 = Swift.Int32()

      /// Customized export features time window for snapshot analysis. Unit is one
      /// day. Default value is 3 weeks. Minimum value is 1 day. Maximum value is
      /// 4000 days.
      public var stalenessDays: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `SnapshotAnalysis`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SnapshotAnalysis().with { $0.disabled = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let disabled = CodingKeys(stringValue: "disabled")
        static let monitoringIntervalDays = CodingKeys(stringValue: "monitoringIntervalDays")
        static let stalenessDays = CodingKeys(stringValue: "stalenessDays")

        static let _knownKeys: Set<Swift.String> = [
          "disabled",
          "monitoringIntervalDays",
          "stalenessDays",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
          self.disabled = value
        }
        if let value = try container.decodeIfPresent(
          Swift.Int32.self, forKey: .monitoringIntervalDays)
        {
          self.monitoringIntervalDays = value
        }
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .stalenessDays) {
          self.stalenessDays = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.disabled, forKey: .disabled)
        try container.encode(self.monitoringIntervalDays, forKey: .monitoringIntervalDays)
        try container.encode(self.stalenessDays, forKey: .stalenessDays)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The type URL for `SnapshotAnalysis`: `"type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.SnapshotAnalysis"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.SnapshotAnalysis"
      }

      /// Initialize an instance of `SnapshotAnalysis` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.SnapshotAnalysis"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `SnapshotAnalysis` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Configuration of the Featurestore's ImportFeature Analysis Based
    /// Monitoring. This type of analysis generates statistics for values of each
    /// Feature imported by every
    /// [ImportFeatureValues][google.cloud.aiplatform.v1.FeaturestoreService.ImportFeatureValues]
    /// operation.
    ///
    /// [google.cloud.aiplatform.v1.FeaturestoreService.ImportFeatureValues]: <doc:FeaturestoreServiceClient/importFeatureValues(request:options:)>
    public struct ImportFeaturesAnalysis: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Whether to enable / disable / inherite default hebavior for import
      /// features analysis.
      public var state: FeaturestoreMonitoringConfig.ImportFeaturesAnalysis.State =
        FeaturestoreMonitoringConfig.ImportFeaturesAnalysis.State()

      /// The baseline used to do anomaly detection for the statistics generated by
      /// import features analysis.
      public var anomalyDetectionBaseline:
        FeaturestoreMonitoringConfig.ImportFeaturesAnalysis.Baseline = FeaturestoreMonitoringConfig
          .ImportFeaturesAnalysis.Baseline()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ImportFeaturesAnalysis`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ImportFeaturesAnalysis().with { $0.state = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let state = CodingKeys(stringValue: "state")
        static let anomalyDetectionBaseline = CodingKeys(stringValue: "anomalyDetectionBaseline")

        static let _knownKeys: Set<Swift.String> = [
          "state",
          "anomalyDetectionBaseline",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          FeaturestoreMonitoringConfig.ImportFeaturesAnalysis.State.self, forKey: .state)
        {
          self.state = value
        }
        if let value = try container.decodeIfPresent(
          FeaturestoreMonitoringConfig.ImportFeaturesAnalysis.Baseline.self,
          forKey: .anomalyDetectionBaseline)
        {
          self.anomalyDetectionBaseline = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.state, forKey: .state)
        try container.encode(self.anomalyDetectionBaseline, forKey: .anomalyDetectionBaseline)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The state defines whether to enable ImportFeature analysis.
      ///
      /// - Note: Adding cases to this enumeration is not considered a breaking change.
      ///   Always include an `@unknown default:` case when switching over this type.
      ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
      ///   expecting specific values to remain unparsed; future releases may promote
      ///   them to named cases.
      public enum State: Codable, Equatable, Hashable, Sendable {
        /// Should not be used.
        case unspecified
        /// The default behavior of whether to enable the monitoring.
        /// EntityType-level config: disabled.
        /// Feature-level config: inherited from the configuration of EntityType
        /// this Feature belongs to.
        case `default`
        /// Explicitly enables import features analysis.
        /// EntityType-level config: by default enables import features analysis
        /// for all Features under it. Feature-level config: enables import
        /// features analysis regardless of the EntityType-level config.
        case enabled
        /// Explicitly disables import features analysis.
        /// EntityType-level config: by default disables import features analysis
        /// for all Features under it. Feature-level config: disables import
        /// features analysis regardless of the EntityType-level config.
        case disabled
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific integer values in this case;
        ///   future releases may promote them to named enum cases.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific string literals in this case;
        ///   future releases may promote them to named enum cases.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .`default`: return 1
          case .enabled: return 2
          case .disabled: return 3
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "STATE_UNSPECIFIED"
          case .`default`: return "DEFAULT"
          case .enabled: return "ENABLED"
          case .disabled: return "DISABLED"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "STATE_UNSPECIFIED": self = .unspecified
          case "DEFAULT": self = .`default`
          case "ENABLED": self = .enabled
          case "DISABLED": self = .disabled
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .`default`
          case 2: self = .enabled
          case 3: self = .disabled
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: any Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: any Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode("STATE_UNSPECIFIED")
          case .`default`: return try container.encode("DEFAULT")
          case .enabled: return try container.encode("ENABLED")
          case .disabled: return try container.encode("DISABLED")
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      /// Defines the baseline to do anomaly detection for feature values imported
      /// by each
      /// [ImportFeatureValues][google.cloud.aiplatform.v1.FeaturestoreService.ImportFeatureValues]
      /// operation.
      ///
      /// [google.cloud.aiplatform.v1.FeaturestoreService.ImportFeatureValues]: <doc:FeaturestoreServiceClient/importFeatureValues(request:options:)>
      ///
      /// - Note: Adding cases to this enumeration is not considered a breaking change.
      ///   Always include an `@unknown default:` case when switching over this type.
      ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
      ///   expecting specific values to remain unparsed; future releases may promote
      ///   them to named cases.
      public enum Baseline: Codable, Equatable, Hashable, Sendable {
        /// Should not be used.
        case unspecified
        /// Choose the later one statistics generated by either most recent
        /// snapshot analysis or previous import features analysis. If non of them
        /// exists, skip anomaly detection and only generate a statistics.
        case latestStats
        /// Use the statistics generated by the most recent snapshot analysis if
        /// exists.
        case mostRecentSnapshotStats
        /// Use the statistics generated by the previous import features analysis
        /// if exists.
        case previousImportFeaturesStats
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific integer values in this case;
        ///   future releases may promote them to named enum cases.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific string literals in this case;
        ///   future releases may promote them to named enum cases.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .latestStats: return 1
          case .mostRecentSnapshotStats: return 2
          case .previousImportFeaturesStats: return 3
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "BASELINE_UNSPECIFIED"
          case .latestStats: return "LATEST_STATS"
          case .mostRecentSnapshotStats: return "MOST_RECENT_SNAPSHOT_STATS"
          case .previousImportFeaturesStats: return "PREVIOUS_IMPORT_FEATURES_STATS"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Baseline/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "BASELINE_UNSPECIFIED": self = .unspecified
          case "LATEST_STATS": self = .latestStats
          case "MOST_RECENT_SNAPSHOT_STATS": self = .mostRecentSnapshotStats
          case "PREVIOUS_IMPORT_FEATURES_STATS": self = .previousImportFeaturesStats
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Baseline/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .latestStats
          case 2: self = .mostRecentSnapshotStats
          case 3: self = .previousImportFeaturesStats
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: any Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: any Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode("BASELINE_UNSPECIFIED")
          case .latestStats: return try container.encode("LATEST_STATS")
          case .mostRecentSnapshotStats: return try container.encode("MOST_RECENT_SNAPSHOT_STATS")
          case .previousImportFeaturesStats:
            return try container.encode("PREVIOUS_IMPORT_FEATURES_STATS")
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      /// The type URL for `ImportFeaturesAnalysis`: `"type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.ImportFeaturesAnalysis"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.ImportFeaturesAnalysis"
      }

      /// Initialize an instance of `ImportFeaturesAnalysis` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.ImportFeaturesAnalysis"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `ImportFeaturesAnalysis` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The config for Featurestore Monitoring threshold.
    public struct ThresholdConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      public var threshold: ThresholdOneOf? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ThresholdConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ThresholdConfig().with { $0.value = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let value = CodingKeys(stringValue: "value")

        static let _knownKeys: Set<Swift.String> = [
          "value"
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var threshold: ThresholdOneOf? = nil
        let thresholdCheckAndSet = {
          if threshold != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'threshold'"))
          }
          threshold = $0
        }
        if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .value) {
          try thresholdCheckAndSet(.value(value))
        }
        self.threshold = threshold
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.threshold {
          switch choice {
          case .value(let value):
            try container.encode(value, forKey: .value)
          }
        }
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public enum ThresholdOneOf: Codable, Equatable, Sendable {
        /// Specify a threshold value that can trigger the alert.
        /// 1. For categorical feature, the distribution distance is calculated by
        /// L-inifinity norm.
        /// 2. For numerical feature, the distribution distance is calculated by
        /// Jensen–Shannon divergence. Each feature must have a non-zero threshold
        /// if they need to be monitored. Otherwise no alert will be triggered for
        /// that feature.
        case value(Swift.Double)
      }

      /// The type URL for `ThresholdConfig`: `"type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.ThresholdConfig"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.ThresholdConfig"
      }

      /// Initialize an instance of `ThresholdConfig` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig.ThresholdConfig"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `ThresholdConfig` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The type URL for `FeaturestoreMonitoringConfig`: `"type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig"
    }

    /// Initialize an instance of `FeaturestoreMonitoringConfig` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.FeaturestoreMonitoringConfig"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `FeaturestoreMonitoringConfig` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
