// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PredictionService || SessionService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Grounding chunk.
  public struct GroundingChunk: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Chunk type.
    public var chunkType: ChunkTypeOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GroundingChunk`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GroundingChunk().with { $0.web = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let web = CodingKeys(stringValue: "web")
      static let retrievedContext = CodingKeys(stringValue: "retrievedContext")
      static let maps = CodingKeys(stringValue: "maps")

      static let _knownKeys: Set<Swift.String> = [
        "web",
        "retrievedContext",
        "maps",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var chunkType: ChunkTypeOneOf? = nil
      let chunkTypeCheckAndSet = {
        if chunkType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'chunkType'"))
        }
        chunkType = $0
      }
      if let web = try container.decodeIfPresent(GroundingChunk.Web.self, forKey: .web) {
        try chunkTypeCheckAndSet(.web(web))
      }
      if let retrievedContext = try container.decodeIfPresent(
        GroundingChunk.RetrievedContext.self, forKey: .retrievedContext)
      {
        try chunkTypeCheckAndSet(.retrievedContext(retrievedContext))
      }
      if let maps = try container.decodeIfPresent(GroundingChunk.Maps.self, forKey: .maps) {
        try chunkTypeCheckAndSet(.maps(maps))
      }
      self.chunkType = chunkType
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.chunkType {
        switch choice {
        case .web(let value):
          try container.encode(value, forKey: .web)
        case .retrievedContext(let value):
          try container.encode(value, forKey: .retrievedContext)
        case .maps(let value):
          try container.encode(value, forKey: .maps)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Chunk from the web.
    public struct Web: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// URI reference of the chunk.
      public var uri: Swift.String? = nil

      /// Title of the chunk.
      public var title: Swift.String? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Web`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Web().with { $0.uri = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let uri = CodingKeys(stringValue: "uri")
        static let title = CodingKeys(stringValue: "title")

        static let _knownKeys: Set<Swift.String> = [
          "uri",
          "title",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.uri = try container.decodeIfPresent(Swift.String.self, forKey: .uri)
        self.title = try container.decodeIfPresent(Swift.String.self, forKey: .title)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.uri, forKey: .uri)
        try container.encodeIfPresent(self.title, forKey: .title)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.GroundingChunk.Web"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Chunk from context retrieved by the retrieval tools.
    public struct RetrievedContext: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// URI reference of the attribution.
      public var uri: Swift.String? = nil

      /// Title of the attribution.
      public var title: Swift.String? = nil

      /// Text of the attribution.
      public var text: Swift.String? = nil

      /// Output only. The full document name for the referenced Vertex AI Search
      /// document.
      public var documentName: Swift.String? = nil

      /// Tool-specific details about the retrieved context.
      public var contextDetails: ContextDetailsOneOf? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `RetrievedContext`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = RetrievedContext().with { $0.ragChunk = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let ragChunk = CodingKeys(stringValue: "ragChunk")
        static let uri = CodingKeys(stringValue: "uri")
        static let title = CodingKeys(stringValue: "title")
        static let text = CodingKeys(stringValue: "text")
        static let documentName = CodingKeys(stringValue: "documentName")

        static let _knownKeys: Set<Swift.String> = [
          "ragChunk",
          "uri",
          "title",
          "text",
          "documentName",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.uri = try container.decodeIfPresent(Swift.String.self, forKey: .uri)
        self.title = try container.decodeIfPresent(Swift.String.self, forKey: .title)
        self.text = try container.decodeIfPresent(Swift.String.self, forKey: .text)
        self.documentName = try container.decodeIfPresent(Swift.String.self, forKey: .documentName)

        var contextDetails: ContextDetailsOneOf? = nil
        let contextDetailsCheckAndSet = {
          if contextDetails != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'contextDetails'"))
          }
          contextDetails = $0
        }
        if let ragChunk = try container.decodeIfPresent(RagChunk.self, forKey: .ragChunk) {
          try contextDetailsCheckAndSet(.ragChunk(ragChunk))
        }
        self.contextDetails = contextDetails
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.uri, forKey: .uri)
        try container.encodeIfPresent(self.title, forKey: .title)
        try container.encodeIfPresent(self.text, forKey: .text)
        try container.encodeIfPresent(self.documentName, forKey: .documentName)

        if let choice = self.contextDetails {
          switch choice {
          case .ragChunk(let value):
            try container.encode(value, forKey: .ragChunk)
          }
        }
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Tool-specific details about the retrieved context.
      public enum ContextDetailsOneOf: Codable, Equatable, Sendable {
        /// Additional context for the RAG retrieval result. This is only populated
        /// when using the RAG retrieval tool.
        indirect case ragChunk(RagChunk)
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.GroundingChunk.RetrievedContext"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// A `Maps` chunk is a piece of evidence that comes from Google Maps,
    /// containing information about places or routes. This is used to provide
    /// the user with rich, location-based information.
    public struct Maps: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// URI reference of the chunk.
      public var uri: Swift.String? = nil

      /// Title of the chunk.
      public var title: Swift.String? = nil

      /// Text of the chunk.
      public var text: Swift.String? = nil

      /// This Place's resource name, in `places/{place_id}` format.  Can be used
      /// to look up the Place.
      public var placeId: Swift.String? = nil

      /// Sources used to generate the place answer.
      /// This includes review snippets and photos that were used to generate the
      /// answer, as well as uris to flag content.
      public var placeAnswerSources: GroundingChunk.Maps.PlaceAnswerSources? = nil

      /// Output only. Route information.
      public var route: GroundingChunk.Maps.Route? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Maps`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Maps().with { $0.uri = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let uri = CodingKeys(stringValue: "uri")
        static let title = CodingKeys(stringValue: "title")
        static let text = CodingKeys(stringValue: "text")
        static let placeId = CodingKeys(stringValue: "placeId")
        static let placeAnswerSources = CodingKeys(stringValue: "placeAnswerSources")
        static let route = CodingKeys(stringValue: "route")

        static let _knownKeys: Set<Swift.String> = [
          "uri",
          "title",
          "text",
          "placeId",
          "placeAnswerSources",
          "route",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.uri = try container.decodeIfPresent(Swift.String.self, forKey: .uri)
        self.title = try container.decodeIfPresent(Swift.String.self, forKey: .title)
        self.text = try container.decodeIfPresent(Swift.String.self, forKey: .text)
        self.placeId = try container.decodeIfPresent(Swift.String.self, forKey: .placeId)
        self.placeAnswerSources = try container.decodeIfPresent(
          GroundingChunk.Maps.PlaceAnswerSources.self, forKey: .placeAnswerSources)
        self.route = try container.decodeIfPresent(GroundingChunk.Maps.Route.self, forKey: .route)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.uri, forKey: .uri)
        try container.encodeIfPresent(self.title, forKey: .title)
        try container.encodeIfPresent(self.text, forKey: .text)
        try container.encodeIfPresent(self.placeId, forKey: .placeId)
        try container.encodeIfPresent(self.placeAnswerSources, forKey: .placeAnswerSources)
        try container.encodeIfPresent(self.route, forKey: .route)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public struct PlaceAnswerSources: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// Snippets of reviews that are used to generate the answer.
        public var reviewSnippets: [GroundingChunk.Maps.PlaceAnswerSources.ReviewSnippet] = []

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `PlaceAnswerSources`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = PlaceAnswerSources().with { $0.reviewSnippets = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let reviewSnippets = CodingKeys(stringValue: "reviewSnippets")

          static let _knownKeys: Set<Swift.String> = [
            "reviewSnippets"
          ]
        }

        public init(from decoder: any Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(
            [GroundingChunk.Maps.PlaceAnswerSources.ReviewSnippet].self, forKey: .reviewSnippets)
          {
            self.reviewSnippets = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.WKTValue.self, forKey: key)
          }
        }

        public func encode(to encoder: any Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.reviewSnippets, forKey: .reviewSnippets)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        /// Encapsulates a review snippet.
        public struct ReviewSnippet: Codable, Equatable, GoogleWKT._AnyPackable,
          Sendable
        {
          /// Id of the review referencing the place.
          public var reviewId: Swift.String = Swift.String()

          /// A link to show the review on Google Maps.
          public var googleMapsUri: Swift.String = Swift.String()

          /// Title of the review.
          public var title: Swift.String = Swift.String()

          @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

          /// Initialize a new instance of `ReviewSnippet`.
          public init() {}

          /// Use `config` to return a new instance of this object, with some fields updated.
          ///
          /// Commonly used to initialize the value, for example:
          ///
          /// ```
          /// let value = ReviewSnippet().with { $0.reviewId = ... }
          /// ```
          public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
            var copy = self
            try config(&copy)
            return copy
          }

          private struct CodingKeys: CodingKey {
            var stringValue: Swift.String
            var intValue: Swift.Int? { nil }
            init(stringValue: Swift.String) { self.stringValue = stringValue }
            init?(intValue: Swift.Int) { nil }

            static let reviewId = CodingKeys(stringValue: "reviewId")
            static let googleMapsUri = CodingKeys(stringValue: "googleMapsUri")
            static let title = CodingKeys(stringValue: "title")

            static let _knownKeys: Set<Swift.String> = [
              "reviewId",
              "googleMapsUri",
              "title",
            ]
          }

          public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reviewId) {
              self.reviewId = value
            }
            if let value = try container.decodeIfPresent(Swift.String.self, forKey: .googleMapsUri)
            {
              self.googleMapsUri = value
            }
            if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
              self.title = value
            }
            for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
              self._unknownFields.json[key.stringValue] = try container.decode(
                GoogleWKT.WKTValue.self, forKey: key)
            }
          }

          public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.reviewId, forKey: .reviewId)
            try container.encode(self.googleMapsUri, forKey: .googleMapsUri)
            try container.encode(self.title, forKey: .title)
            for (key, value) in self._unknownFields.json {
              try container.encode(value, forKey: CodingKeys(stringValue: key))
            }
          }

          public static var _anyTypeUrl: Swift.String {
            return
              "type.googleapis.com/google.cloud.aiplatform.v1.GroundingChunk.Maps.PlaceAnswerSources.ReviewSnippet"
          }
          public init(fromAny any: GoogleWKT.WKTAny) throws {
            self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
          }
          public func _pack() throws -> GoogleWKT.WKTStruct {
            return try GoogleWKT._slowAnySerialize(message: self)
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.aiplatform.v1.GroundingChunk.Maps.PlaceAnswerSources"
        }
        public init(fromAny any: GoogleWKT.WKTAny) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleWKT.WKTStruct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      /// Route information from Google Maps.
      public struct Route: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// The total distance of the route, in meters.
        public var distanceMeters: Swift.Int32 = Swift.Int32()

        /// The total duration of the route.
        public var duration: GoogleWKT.WKTDuration? = nil

        /// An encoded polyline of the route. See
        /// https://developers.google.com/maps/documentation/utilities/polylinealgorithm
        public var encodedPolyline: Swift.String = Swift.String()

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `Route`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Route().with { $0.distanceMeters = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let distanceMeters = CodingKeys(stringValue: "distanceMeters")
          static let duration = CodingKeys(stringValue: "duration")
          static let encodedPolyline = CodingKeys(stringValue: "encodedPolyline")

          static let _knownKeys: Set<Swift.String> = [
            "distanceMeters",
            "duration",
            "encodedPolyline",
          ]
        }

        public init(from decoder: any Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .distanceMeters) {
            self.distanceMeters = value
          }
          self.duration = try container.decodeIfPresent(
            GoogleWKT.WKTDuration.self, forKey: .duration)
          if let value = try container.decodeIfPresent(Swift.String.self, forKey: .encodedPolyline)
          {
            self.encodedPolyline = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.WKTValue.self, forKey: key)
          }
        }

        public func encode(to encoder: any Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.distanceMeters, forKey: .distanceMeters)
          try container.encodeIfPresent(self.duration, forKey: .duration)
          try container.encode(self.encodedPolyline, forKey: .encodedPolyline)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return "type.googleapis.com/google.cloud.aiplatform.v1.GroundingChunk.Maps.Route"
        }
        public init(fromAny any: GoogleWKT.WKTAny) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleWKT.WKTStruct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.GroundingChunk.Maps"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Chunk type.
    public enum ChunkTypeOneOf: Codable, Equatable, Sendable {
      /// Grounding chunk from the web.
      indirect case web(GroundingChunk.Web)
      /// Grounding chunk from context retrieved by the retrieval tools.
      indirect case retrievedContext(GroundingChunk.RetrievedContext)
      /// Grounding chunk from Google Maps.
      indirect case maps(GroundingChunk.Maps)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.GroundingChunk"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
