// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if VertexRagDataService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Response message for
  /// [VertexRagDataService.ImportRagFiles][google.cloud.aiplatform.v1.VertexRagDataService.ImportRagFiles].
  ///
  /// [google.cloud.aiplatform.v1.VertexRagDataService.ImportRagFiles]: <doc:VertexRagDataServiceClient/importRagFiles(request:options:)>
  public struct ImportRagFilesResponse: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The number of RagFiles that had been imported into the RagCorpus.
    public var importedRagFilesCount: Swift.Int64 = Swift.Int64()

    /// The number of RagFiles that had failed while importing into the RagCorpus.
    public var failedRagFilesCount: Swift.Int64 = Swift.Int64()

    /// The number of RagFiles that was skipped while importing into the RagCorpus.
    public var skippedRagFilesCount: Swift.Int64 = Swift.Int64()

    /// The location into which the partial failures were written.
    public var partialFailureSink: PartialFailureSinkOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ImportRagFilesResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportRagFilesResponse().with { $0.partialFailuresGcsPath = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let partialFailuresGcsPath = CodingKeys(stringValue: "partialFailuresGcsPath")
      static let partialFailuresBigqueryTable = CodingKeys(
        stringValue: "partialFailuresBigqueryTable")
      static let importedRagFilesCount = CodingKeys(stringValue: "importedRagFilesCount")
      static let failedRagFilesCount = CodingKeys(stringValue: "failedRagFilesCount")
      static let skippedRagFilesCount = CodingKeys(stringValue: "skippedRagFilesCount")

      static let _knownKeys: Set<Swift.String> = [
        "partialFailuresGcsPath",
        "partialFailuresBigqueryTable",
        "importedRagFilesCount",
        "failedRagFilesCount",
        "skippedRagFilesCount",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .importedRagFilesCount)
      {
        self.importedRagFilesCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .failedRagFilesCount) {
        self.failedRagFilesCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .skippedRagFilesCount)
      {
        self.skippedRagFilesCount = value
      }

      var partialFailureSink: PartialFailureSinkOneOf? = nil
      let partialFailureSinkCheckAndSet = {
        if partialFailureSink != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'partialFailureSink'"))
        }
        partialFailureSink = $0
      }
      if let partialFailuresGcsPath = try container.decodeIfPresent(
        Swift.String.self, forKey: .partialFailuresGcsPath)
      {
        try partialFailureSinkCheckAndSet(.partialFailuresGcsPath(partialFailuresGcsPath))
      }
      if let partialFailuresBigqueryTable = try container.decodeIfPresent(
        Swift.String.self, forKey: .partialFailuresBigqueryTable)
      {
        try partialFailureSinkCheckAndSet(
          .partialFailuresBigqueryTable(partialFailuresBigqueryTable))
      }
      self.partialFailureSink = partialFailureSink
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.importedRagFilesCount, forKey: .importedRagFilesCount)
      try container.encode(self.failedRagFilesCount, forKey: .failedRagFilesCount)
      try container.encode(self.skippedRagFilesCount, forKey: .skippedRagFilesCount)

      if let choice = self.partialFailureSink {
        switch choice {
        case .partialFailuresGcsPath(let value):
          try container.encode(value, forKey: .partialFailuresGcsPath)
        case .partialFailuresBigqueryTable(let value):
          try container.encode(value, forKey: .partialFailuresBigqueryTable)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The location into which the partial failures were written.
    public enum PartialFailureSinkOneOf: Codable, Equatable, Sendable {
      /// The Google Cloud Storage path into which the partial failures were
      /// written.
      case partialFailuresGcsPath(Swift.String)
      /// The BigQuery table into which the partial failures were written.
      case partialFailuresBigqueryTable(Swift.String)
    }

    /// The type URL for `ImportRagFilesResponse`: `"type.googleapis.com/google.cloud.aiplatform.v1.ImportRagFilesResponse"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ImportRagFilesResponse"
    }

    /// Initialize an instance of `ImportRagFilesResponse` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.ImportRagFilesResponse"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ImportRagFilesResponse` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
