// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if MetadataService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// A subgraph of the overall lineage graph. Event edges connect Artifact and
  /// Execution nodes.
  public struct LineageSubgraph: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The Artifact nodes in the subgraph.
    public var artifacts: [Artifact] = []

    /// The Execution nodes in the subgraph.
    public var executions: [Execution] = []

    /// The Event edges between Artifacts and Executions in the subgraph.
    public var events: [Event] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LineageSubgraph`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LineageSubgraph().with { $0.artifacts = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let artifacts = CodingKeys(stringValue: "artifacts")
      static let executions = CodingKeys(stringValue: "executions")
      static let events = CodingKeys(stringValue: "events")

      static let _knownKeys: Set<Swift.String> = [
        "artifacts",
        "executions",
        "events",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Artifact].self, forKey: .artifacts) {
        self.artifacts = value
      }
      if let value = try container.decodeIfPresent([Execution].self, forKey: .executions) {
        self.executions = value
      }
      if let value = try container.decodeIfPresent([Event].self, forKey: .events) {
        self.events = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.artifacts, forKey: .artifacts)
      try container.encode(self.executions, forKey: .executions)
      try container.encode(self.events, forKey: .events)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `LineageSubgraph`: `"type.googleapis.com/google.cloud.aiplatform.v1.LineageSubgraph"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.LineageSubgraph"
    }

    /// Initialize an instance of `LineageSubgraph` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.LineageSubgraph"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `LineageSubgraph` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
