// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if EvaluationService
  import Foundation
  public import GoogleRpc
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Result for a single metric on a single instance.
  public struct MetricResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The score for the metric.
    /// Please refer to each metric's documentation for the meaning of the score.
    public var score: Swift.Float? = nil

    /// Output only. The explanation for the metric result.
    public var explanation: Swift.String? = nil

    /// Output only. The error status for the metric result.
    public var error: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MetricResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MetricResult().with { $0.score = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let score = CodingKeys(stringValue: "score")
      static let explanation = CodingKeys(stringValue: "explanation")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "score",
        "explanation",
        "error",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.score = try container.decodeIfPresent(Swift.Float.self, forKey: .score)
      self.explanation = try container.decodeIfPresent(Swift.String.self, forKey: .explanation)
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.score, forKey: .score)
      try container.encodeIfPresent(self.explanation, forKey: .explanation)
      try container.encodeIfPresent(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `MetricResult`: `"type.googleapis.com/google.cloud.aiplatform.v1.MetricResult"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.MetricResult"
    }

    /// Initialize an instance of `MetricResult` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.MetricResult"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `MetricResult` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
