// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if EndpointService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Configuration for logging request-response to a BigQuery table.
  public struct PredictRequestResponseLoggingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// If logging is enabled or not.
    public var enabled: Swift.Bool = Swift.Bool()

    /// Percentage of requests to be logged, expressed as a fraction in
    /// range(0,1].
    public var samplingRate: Swift.Double = Swift.Double()

    /// BigQuery table for logging.
    /// If only given a project, a new dataset will be created with name
    /// `logging_<endpoint-display-name>_<endpoint-id>` where
    /// <endpoint-display-name> will be made BigQuery-dataset-name compatible (e.g.
    /// most special characters will become underscores). If no table name is
    /// given, a new table will be created with name `request_response_logging`
    public var bigqueryDestination: BigQueryDestination? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PredictRequestResponseLoggingConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PredictRequestResponseLoggingConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enabled = CodingKeys(stringValue: "enabled")
      static let samplingRate = CodingKeys(stringValue: "samplingRate")
      static let bigqueryDestination = CodingKeys(stringValue: "bigqueryDestination")

      static let _knownKeys: Set<Swift.String> = [
        "enabled",
        "samplingRate",
        "bigqueryDestination",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
        self.enabled = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .samplingRate) {
        self.samplingRate = value
      }
      self.bigqueryDestination = try container.decodeIfPresent(
        BigQueryDestination.self, forKey: .bigqueryDestination)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enabled, forKey: .enabled)
      try container.encode(self.samplingRate, forKey: .samplingRate)
      try container.encodeIfPresent(self.bigqueryDestination, forKey: .bigqueryDestination)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `PredictRequestResponseLoggingConfig`: `"type.googleapis.com/google.cloud.aiplatform.v1.PredictRequestResponseLoggingConfig"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.PredictRequestResponseLoggingConfig"
    }

    /// Initialize an instance of `PredictRequestResponseLoggingConfig` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.PredictRequestResponseLoggingConfig"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `PredictRequestResponseLoggingConfig` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
