// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if MetadataService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Request message for
  /// [MetadataService.QueryArtifactLineageSubgraph][google.cloud.aiplatform.v1.MetadataService.QueryArtifactLineageSubgraph].
  ///
  /// [google.cloud.aiplatform.v1.MetadataService.QueryArtifactLineageSubgraph]: <doc:MetadataServiceClient/queryArtifactLineageSubgraph(request:options:)>
  public struct QueryArtifactLineageSubgraphRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the Artifact whose Lineage needs to be
    /// retrieved as a LineageSubgraph. Format:
    /// `projects/{project}/locations/{location}/metadataStores/{metadatastore}/artifacts/{artifact}`
    ///
    /// The request may error with FAILED_PRECONDITION if the number of Artifacts,
    /// the number of Executions, or the number of Events that would be returned
    /// for the Context exceeds 1000.
    public var artifact: Swift.String = Swift.String()

    /// Specifies the size of the lineage graph in terms of number of hops from the
    /// specified artifact.
    /// Negative Value: INVALID_ARGUMENT error is returned
    /// 0: Only input artifact is returned.
    /// No value: Transitive closure is performed to return the complete graph.
    public var maxHops: Swift.Int32 = Swift.Int32()

    /// Filter specifying the boolean condition for the Artifacts to satisfy in
    /// order to be part of the Lineage Subgraph.
    /// The syntax to define filter query is based on https://google.aip.dev/160.
    /// The supported set of filters include the following:
    ///
    /// *  **Attribute filtering**:
    ///    For example: `display_name = "test"`
    ///    Supported fields include: `name`, `display_name`, `uri`, `state`,
    ///    `schema_title`, `create_time`, and `update_time`.
    ///    Time fields, such as `create_time` and `update_time`, require values
    ///    specified in RFC-3339 format.
    ///    For example: `create_time = "2020-11-19T11:30:00-04:00"`
    /// *  **Metadata field**:
    ///    To filter on metadata fields use traversal operation as follows:
    ///    `metadata.<field_name>.<type_value>`.
    ///    For example: `metadata.field_1.number_value = 10.0`
    ///    In case the field name contains special characters (such as colon), one
    ///    can embed it inside double quote.
    ///    For example: `metadata."field:1".number_value = 10.0`
    ///
    /// Each of the above supported filter types can be combined together using
    /// logical operators (`AND` & `OR`). Maximum nested expression depth allowed
    /// is 5.
    ///
    /// For example: `display_name = "test" AND metadata.field1.bool_value = true`.
    public var filter: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QueryArtifactLineageSubgraphRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QueryArtifactLineageSubgraphRequest().with { $0.artifact = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let artifact = CodingKeys(stringValue: "artifact")
      static let maxHops = CodingKeys(stringValue: "maxHops")
      static let filter = CodingKeys(stringValue: "filter")

      static let _knownKeys: Set<Swift.String> = [
        "artifact",
        "maxHops",
        "filter",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .artifact) {
        self.artifact = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxHops) {
        self.maxHops = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
        self.filter = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.artifact, forKey: .artifact)
      try container.encode(self.maxHops, forKey: .maxHops)
      try container.encode(self.filter, forKey: .filter)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.QueryArtifactLineageSubgraphRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
