// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ReasoningEngineService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleCloudLocation
  @_spi(GoogleCloudInternal) public import GoogleIAMV1
  @_spi(GoogleCloudInternal) public import GoogleLongRunning
  @_spi(GoogleCloudInternal) public import GoogleWKT
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// A service for managing Vertex AI's Reasoning Engines.
  ///
  /// @Snippet(path: "ReasoningEngineServiceQuickstart")
  public final class ReasoningEngineServiceClient: Clients.ReasoningEngineServiceProtocol, Sendable
  {
    let inner: any Clients.ReasoningEngineServiceStub
    let pollingErrorPolicy: any GoogleGax.PollingErrorPolicy
    let pollingBackoffPolicy: any GoogleGax.PollingBackoffPolicy

    /// Creates a new `ReasoningEngineServiceClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.ReasoningEngineServiceStub =
        try Clients.ReasoningEngineServiceTransport(options)
      inner = Clients.ReasoningEngineServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.ReasoningEngineServiceLogging(inner, logger: logger)
      }
      self.inner = inner
      self.pollingErrorPolicy = options.pollingErrorPolicy
      self.pollingBackoffPolicy = options.pollingBackoffPolicy
    }

    /// Creates a reasoning engine.
    ///
    /// @Snippet(path: "ReasoningEngineService_CreateReasoningEngine")
    public func createReasoningEngine(
      request: CreateReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.createReasoningEngine(request: request, options: options)
    }

    /// Creates a reasoning engine.
    ///
    /// @Snippet(path: "ReasoningEngineService_CreateReasoningEngine")
    public func createReasoningEnginePollingUntilDone(
      request: CreateReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> ReasoningEngine {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<ReasoningEngine>.State in
        return try op._extractStatus(ReasoningEngine.self)
      }
      let rawOp = try await self.createReasoningEngine(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<ReasoningEngine>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      return try await poller.wait()
    }

    /// Gets a reasoning engine.
    ///
    /// @Snippet(path: "ReasoningEngineService_GetReasoningEngine")
    public func getReasoningEngine(
      request: GetReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ReasoningEngine {
      try await self.inner.getReasoningEngine(request: request, options: options)
    }

    /// Lists reasoning engines in a location.
    ///
    /// @Snippet(path: "ReasoningEngineService_ListReasoningEngines")
    public func listReasoningEngines(
      request: ListReasoningEnginesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListReasoningEnginesResponse {
      try await self.inner.listReasoningEngines(request: request, options: options)
    }

    /// Updates a reasoning engine.
    ///
    /// @Snippet(path: "ReasoningEngineService_UpdateReasoningEngine")
    public func updateReasoningEngine(
      request: UpdateReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.updateReasoningEngine(request: request, options: options)
    }

    /// Updates a reasoning engine.
    ///
    /// @Snippet(path: "ReasoningEngineService_UpdateReasoningEngine")
    public func updateReasoningEnginePollingUntilDone(
      request: UpdateReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> ReasoningEngine {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<ReasoningEngine>.State in
        return try op._extractStatus(ReasoningEngine.self)
      }
      let rawOp = try await self.updateReasoningEngine(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<ReasoningEngine>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      return try await poller.wait()
    }

    /// Deletes a reasoning engine.
    ///
    /// @Snippet(path: "ReasoningEngineService_DeleteReasoningEngine")
    public func deleteReasoningEngine(
      request: DeleteReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.deleteReasoningEngine(request: request, options: options)
    }

    /// Deletes a reasoning engine.
    ///
    /// @Snippet(path: "ReasoningEngineService_DeleteReasoningEngine")
    public func deleteReasoningEnginePollingUntilDone(
      request: DeleteReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        return try op._extractStatusEmpty()
      }
      let rawOp = try await self.deleteReasoningEngine(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      try await poller.wait()
    }

    /// Lists information about the supported locations for this service.
    ///
    /// @Snippet(path: "ReasoningEngineService_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "ReasoningEngineService_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Sets the access control policy on the specified resource. Replaces
    /// any existing policy.
    ///
    /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
    /// errors.
    ///
    /// @Snippet(path: "ReasoningEngineService_SetIamPolicy")
    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self.inner.setIamPolicy(request: request, options: options)
    }

    /// Gets the access control policy for a resource. Returns an empty policy
    /// if the resource exists and does not have a policy set.
    ///
    /// @Snippet(path: "ReasoningEngineService_GetIamPolicy")
    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self.inner.getIamPolicy(request: request, options: options)
    }

    /// Returns permissions that a caller has on the specified resource. If the
    /// resource does not exist, this will return an empty set of
    /// permissions, not a `NOT_FOUND` error.
    ///
    /// Note: This operation is designed to be used for building
    /// permission-aware UIs and command-line tools, not for authorization
    /// checking. This operation may "fail open" without warning.
    ///
    /// @Snippet(path: "ReasoningEngineService_TestIamPermissions")
    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ReasoningEngineService_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ReasoningEngineService_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ReasoningEngineService_DeleteOperation")
    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ReasoningEngineService_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ReasoningEngineService_WaitOperation")
    public func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.waitOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `ReasoningEngineServiceClient`.
    ///
    /// To mock `ReasoningEngineServiceClient` change your functions to receive
    /// `some ReasoningEngineServiceProtocol` or `any ReasoningEngineServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol ReasoningEngineServiceProtocol: Sendable {
      /// See `ReasoningEngineServiceClient.createReasoningEngine`.
      func createReasoningEngine(
        request: CreateReasoningEngineRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `ReasoningEngineServiceClient.createReasoningEngine`.
      func createReasoningEnginePollingUntilDone(
        request: CreateReasoningEngineRequest, options: GoogleGax.RequestOptions
      ) async throws -> ReasoningEngine

      /// See `ReasoningEngineServiceClient.getReasoningEngine`.
      func getReasoningEngine(
        request: GetReasoningEngineRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReasoningEngine

      /// See `ReasoningEngineServiceClient.listReasoningEngines`.
      func listReasoningEngines(
        request: ListReasoningEnginesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListReasoningEnginesResponse

      /// See `ReasoningEngineServiceClient.updateReasoningEngine`.
      func updateReasoningEngine(
        request: UpdateReasoningEngineRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `ReasoningEngineServiceClient.updateReasoningEngine`.
      func updateReasoningEnginePollingUntilDone(
        request: UpdateReasoningEngineRequest, options: GoogleGax.RequestOptions
      ) async throws -> ReasoningEngine

      /// See `ReasoningEngineServiceClient.deleteReasoningEngine`.
      func deleteReasoningEngine(
        request: DeleteReasoningEngineRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `ReasoningEngineServiceClient.deleteReasoningEngine`.
      func deleteReasoningEnginePollingUntilDone(
        request: DeleteReasoningEngineRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `ReasoningEngineServiceClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `ReasoningEngineServiceClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `ReasoningEngineServiceClient.setIamPolicy`.
      func setIamPolicy(
        request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      /// See `ReasoningEngineServiceClient.getIamPolicy`.
      func getIamPolicy(
        request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      /// See `ReasoningEngineServiceClient.testIamPermissions`.
      func testIamPermissions(
        request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

      /// See `ReasoningEngineServiceClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `ReasoningEngineServiceClient.deleteOperation`.
      func deleteOperation(
        request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `ReasoningEngineServiceClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `ReasoningEngineServiceClient.waitOperation`.
      func waitOperation(
        request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation
    }
  }

  // Default implementations
  extension Clients.ReasoningEngineServiceProtocol {
    public func createReasoningEngine(request: CreateReasoningEngineRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.createReasoningEngine(request: request, options: .init())
    }

    public func createReasoningEngine(
      request: CreateReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createReasoningEnginePollingUntilDone(request: CreateReasoningEngineRequest)
      async throws -> ReasoningEngine
    {
      return try await self.createReasoningEnginePollingUntilDone(
        request: request, options: .init())
    }

    public func createReasoningEnginePollingUntilDone(
      request: CreateReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> ReasoningEngine {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createReasoningEnginePollingUntilDone(
      parent: Swift.String,
      reasoningEngine: ReasoningEngine?,
    ) async throws -> ReasoningEngine {
      let request = CreateReasoningEngineRequest().with {
        $0.parent = parent
        $0.reasoningEngine = reasoningEngine
      }
      return try await self.createReasoningEnginePollingUntilDone(request: request)
    }

    public func getReasoningEngine(request: GetReasoningEngineRequest) async throws
      -> GoogleCloudAIPlatformV1.ReasoningEngine
    {
      try await self.getReasoningEngine(request: request, options: .init())
    }

    public func getReasoningEngine(
      request: GetReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ReasoningEngine {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getReasoningEngine(
      name: Swift.String,
    ) async throws -> GoogleCloudAIPlatformV1.ReasoningEngine {
      let request = GetReasoningEngineRequest().with {
        $0.name = name
      }
      return try await self.getReasoningEngine(request: request)
    }

    public func listReasoningEngines(request: ListReasoningEnginesRequest) async throws
      -> GoogleCloudAIPlatformV1.ListReasoningEnginesResponse
    {
      try await self.listReasoningEngines(request: request, options: .init())
    }

    public func listReasoningEngines(
      request: ListReasoningEnginesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.ListReasoningEnginesResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listReasoningEnginesByItems(
      request: ListReasoningEnginesRequest
    ) -> some AsyncSequence<ReasoningEngine, any Swift.Error> & Sendable {
      self.listReasoningEnginesByItems(request: request, options: .init())
    }

    /// Lists reasoning engines in a location.
    ///
    /// @Snippet(path: "ReasoningEngineService_ListReasoningEngines")
    public func listReasoningEnginesByItems(
      request: ListReasoningEnginesRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<ReasoningEngine, any Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudAIPlatformV1.ListReasoningEnginesResponse in
        var request = request
        request.pageToken = token
        return try await self.listReasoningEngines(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listReasoningEnginesByItems(
      parent: Swift.String,
    ) -> some AsyncSequence<ReasoningEngine, any Swift.Error> & Sendable {
      let request = ListReasoningEnginesRequest().with {
        $0.parent = parent
      }
      return self.listReasoningEnginesByItems(request: request)
    }

    public func updateReasoningEngine(request: UpdateReasoningEngineRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.updateReasoningEngine(request: request, options: .init())
    }

    public func updateReasoningEngine(
      request: UpdateReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateReasoningEnginePollingUntilDone(request: UpdateReasoningEngineRequest)
      async throws -> ReasoningEngine
    {
      return try await self.updateReasoningEnginePollingUntilDone(
        request: request, options: .init())
    }

    public func updateReasoningEnginePollingUntilDone(
      request: UpdateReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> ReasoningEngine {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateReasoningEnginePollingUntilDone(
      reasoningEngine: ReasoningEngine?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> ReasoningEngine {
      let request = UpdateReasoningEngineRequest().with {
        $0.reasoningEngine = reasoningEngine
        $0.updateMask = updateMask
      }
      return try await self.updateReasoningEnginePollingUntilDone(request: request)
    }

    public func deleteReasoningEngine(request: DeleteReasoningEngineRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.deleteReasoningEngine(request: request, options: .init())
    }

    public func deleteReasoningEngine(
      request: DeleteReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteReasoningEnginePollingUntilDone(request: DeleteReasoningEngineRequest)
      async throws
    {
      try await self.deleteReasoningEnginePollingUntilDone(request: request, options: .init())
    }

    public func deleteReasoningEnginePollingUntilDone(
      request: DeleteReasoningEngineRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteReasoningEnginePollingUntilDone(
      name: Swift.String,
    ) async throws {
      let request = DeleteReasoningEngineRequest().with {
        $0.name = name
      }
      try await self.deleteReasoningEnginePollingUntilDone(request: request)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest
    ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
      self.listLocationsByItems(request: request, options: .init())
    }

    /// Lists information about the supported locations for this service.
    ///
    /// @Snippet(path: "ReasoningEngineService_ListLocations")
    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
      -> GoogleIAMV1.Policy
    {
      try await self.setIamPolicy(request: request, options: .init())
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
      -> GoogleIAMV1.Policy
    {
      try await self.getIamPolicy(request: request, options: .init())
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse
    {
      try await self.testIamPermissions(request: request, options: .init())
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest
    ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
      self.listOperationsByItems(request: request, options: .init())
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ReasoningEngineService_ListOperations")
    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listOperationsByItems(
      name: Swift.String,
      filter: Swift.String,
    ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return self.listOperationsByItems(request: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
      try await self.deleteOperation(request: request, options: .init())
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.DeleteOperationRequest().with {
        $0.name = name
      }
      try await self.deleteOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }

    public func waitOperation(request: GoogleLongRunning.WaitOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.waitOperation(request: request, options: .init())
    }

    public func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'ReasoningEngineService' trait in Package.swift to use this client."
  )
  public final class ReasoningEngineServiceClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'ReasoningEngineService' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
