// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if EvaluationService || GenAiTuningService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Spec for rouge score metric - calculates the recall of n-grams in prediction
  /// as compared to reference - returns a score ranging between 0 and 1.
  public struct RougeSpec: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Supported rouge types are rougen[1-9], rougeL, and rougeLsum.
    public var rougeType: Swift.String = Swift.String()

    /// Optional. Whether to use stemmer to compute rouge score.
    public var useStemmer: Swift.Bool = Swift.Bool()

    /// Optional. Whether to split summaries while using rougeLsum.
    public var splitSummaries: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RougeSpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RougeSpec().with { $0.rougeType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let rougeType = CodingKeys(stringValue: "rougeType")
      static let useStemmer = CodingKeys(stringValue: "useStemmer")
      static let splitSummaries = CodingKeys(stringValue: "splitSummaries")

      static let _knownKeys: Set<Swift.String> = [
        "rougeType",
        "useStemmer",
        "splitSummaries",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rougeType) {
        self.rougeType = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useStemmer) {
        self.useStemmer = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .splitSummaries) {
        self.splitSummaries = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.rougeType, forKey: .rougeType)
      try container.encode(self.useStemmer, forKey: .useStemmer)
      try container.encode(self.splitSummaries, forKey: .splitSummaries)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `RougeSpec`: `"type.googleapis.com/google.cloud.aiplatform.v1.RougeSpec"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.RougeSpec"
    }

    /// Initialize an instance of `RougeSpec` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.RougeSpec"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `RougeSpec` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
