// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GenAiCacheService || GenAiTuningService || LlmUtilityService || PredictionService || VertexRagService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Schema is used to define the format of input/output data. Represents a select
  /// subset of an [OpenAPI 3.0 schema
  /// object](https://spec.openapis.org/oas/v3.0.3#schema-object). More fields may
  /// be added in the future as needed.
  public struct Schema: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The type of the data.
    public var type: GoogleCloudAIPlatformV1.Type_ = GoogleCloudAIPlatformV1.Type_()

    /// Optional. The format of the data.
    /// Supported formats:
    ///  for NUMBER type: "float", "double"
    ///  for INTEGER type: "int32", "int64"
    ///  for STRING type: "email", "byte", etc
    public var format: Swift.String = Swift.String()

    /// Optional. The title of the Schema.
    public var title: Swift.String = Swift.String()

    /// Optional. The description of the data.
    public var description: Swift.String = Swift.String()

    /// Optional. Indicates if the value may be null.
    public var nullable: Swift.Bool = Swift.Bool()

    /// Optional. Default value of the data.
    public var `default`: GoogleWKT.WKTValue? = nil

    /// Optional. SCHEMA FIELDS FOR TYPE ARRAY
    /// Schema of the elements of Type.ARRAY.
    public var items: GoogleWKT.WKTRecursive<Schema>? = nil

    /// Optional. Minimum number of the elements for Type.ARRAY.
    public var minItems: Swift.Int64 = Swift.Int64()

    /// Optional. Maximum number of the elements for Type.ARRAY.
    public var maxItems: Swift.Int64 = Swift.Int64()

    /// Optional. Possible values of the element of primitive type with enum
    /// format. Examples:
    /// 1. We can define direction as :
    /// {type:STRING, format:enum, enum:["EAST", NORTH", "SOUTH", "WEST"]}
    /// 2. We can define apartment number as :
    /// {type:INTEGER, format:enum, enum:["101", "201", "301"]}
    public var `enum`: [Swift.String] = []

    /// Optional. SCHEMA FIELDS FOR TYPE OBJECT
    /// Properties of Type.OBJECT.
    public var properties: [Swift.String: Schema] = [:]

    /// Optional. The order of the properties.
    /// Not a standard field in open api spec. Only used to support the order of
    /// the properties.
    public var propertyOrdering: [Swift.String] = []

    /// Optional. Required properties of Type.OBJECT.
    public var `required`: [Swift.String] = []

    /// Optional. Minimum number of the properties for Type.OBJECT.
    public var minProperties: Swift.Int64 = Swift.Int64()

    /// Optional. Maximum number of the properties for Type.OBJECT.
    public var maxProperties: Swift.Int64 = Swift.Int64()

    /// Optional. SCHEMA FIELDS FOR TYPE INTEGER and NUMBER
    /// Minimum value of the Type.INTEGER and Type.NUMBER
    public var minimum: Swift.Double = Swift.Double()

    /// Optional. Maximum value of the Type.INTEGER and Type.NUMBER
    public var maximum: Swift.Double = Swift.Double()

    /// Optional. SCHEMA FIELDS FOR TYPE STRING
    /// Minimum length of the Type.STRING
    public var minLength: Swift.Int64 = Swift.Int64()

    /// Optional. Maximum length of the Type.STRING
    public var maxLength: Swift.Int64 = Swift.Int64()

    /// Optional. Pattern of the Type.STRING to restrict a string to a regular
    /// expression.
    public var pattern: Swift.String = Swift.String()

    /// Optional. Example of the object. Will only populated when the object is the
    /// root.
    public var example: GoogleWKT.WKTValue? = nil

    /// Optional. The value should be validated against any (one or more) of the
    /// subschemas in the list.
    public var anyOf: [Schema] = []

    /// Optional. Can either be a boolean or an object; controls the presence of
    /// additional properties.
    public var additionalProperties: GoogleWKT.WKTValue? = nil

    /// Optional. Allows indirect references between schema nodes. The value should
    /// be a valid reference to a child of the root `defs`.
    ///
    /// For example, the following schema defines a reference to a schema node
    /// named "Pet":
    ///
    /// type: object
    /// properties:
    ///   pet:
    ///     ref: #/defs/Pet
    /// defs:
    ///   Pet:
    ///     type: object
    ///     properties:
    ///       name:
    ///         type: string
    ///
    /// The value of the "pet" property is a reference to the schema node
    /// named "Pet".
    /// See details in
    /// https://json-schema.org/understanding-json-schema/structuring
    public var ref: Swift.String = Swift.String()

    /// Optional. A map of definitions for use by `ref`
    /// Only allowed at the root of the schema.
    public var defs: [Swift.String: Schema] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Schema`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Schema().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let type = CodingKeys(stringValue: "type")
      static let format = CodingKeys(stringValue: "format")
      static let title = CodingKeys(stringValue: "title")
      static let description = CodingKeys(stringValue: "description")
      static let nullable = CodingKeys(stringValue: "nullable")
      static let `default` = CodingKeys(stringValue: "default")
      static let items = CodingKeys(stringValue: "items")
      static let minItems = CodingKeys(stringValue: "minItems")
      static let maxItems = CodingKeys(stringValue: "maxItems")
      static let `enum` = CodingKeys(stringValue: "enum")
      static let properties = CodingKeys(stringValue: "properties")
      static let propertyOrdering = CodingKeys(stringValue: "propertyOrdering")
      static let `required` = CodingKeys(stringValue: "required")
      static let minProperties = CodingKeys(stringValue: "minProperties")
      static let maxProperties = CodingKeys(stringValue: "maxProperties")
      static let minimum = CodingKeys(stringValue: "minimum")
      static let maximum = CodingKeys(stringValue: "maximum")
      static let minLength = CodingKeys(stringValue: "minLength")
      static let maxLength = CodingKeys(stringValue: "maxLength")
      static let pattern = CodingKeys(stringValue: "pattern")
      static let example = CodingKeys(stringValue: "example")
      static let anyOf = CodingKeys(stringValue: "anyOf")
      static let additionalProperties = CodingKeys(stringValue: "additionalProperties")
      static let ref = CodingKeys(stringValue: "ref")
      static let defs = CodingKeys(stringValue: "defs")

      static let _knownKeys: Set<Swift.String> = [
        "type",
        "format",
        "title",
        "description",
        "nullable",
        "default",
        "items",
        "minItems",
        "maxItems",
        "enum",
        "properties",
        "propertyOrdering",
        "required",
        "minProperties",
        "maxProperties",
        "minimum",
        "maximum",
        "minLength",
        "maxLength",
        "pattern",
        "example",
        "anyOf",
        "additionalProperties",
        "ref",
        "defs",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        GoogleCloudAIPlatformV1.Type_.self, forKey: .type)
      {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .format) {
        self.format = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
        self.title = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .nullable) {
        self.nullable = value
      }
      self.`default` = try container.decodeIfPresent(GoogleWKT.WKTValue.self, forKey: .`default`)
      self.items = try container.decodeIfPresent(
        GoogleWKT.WKTRecursive<Schema>.self, forKey: .items)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .minItems) {
        self.minItems = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxItems) {
        self.maxItems = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .`enum`) {
        self.`enum` = value
      }
      if let value = try container.decodeIfPresent([Swift.String: Schema].self, forKey: .properties)
      {
        self.properties = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .propertyOrdering) {
        self.propertyOrdering = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .`required`) {
        self.`required` = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .minProperties) {
        self.minProperties = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxProperties) {
        self.maxProperties = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .minimum) {
        self.minimum = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .maximum) {
        self.maximum = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .minLength) {
        self.minLength = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxLength) {
        self.maxLength = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pattern) {
        self.pattern = value
      }
      self.example = try container.decodeIfPresent(GoogleWKT.WKTValue.self, forKey: .example)
      if let value = try container.decodeIfPresent([Schema].self, forKey: .anyOf) {
        self.anyOf = value
      }
      self.additionalProperties = try container.decodeIfPresent(
        GoogleWKT.WKTValue.self, forKey: .additionalProperties)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ref) {
        self.ref = value
      }
      if let value = try container.decodeIfPresent([Swift.String: Schema].self, forKey: .defs) {
        self.defs = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.format, forKey: .format)
      try container.encode(self.title, forKey: .title)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.nullable, forKey: .nullable)
      try container.encodeIfPresent(self.`default`, forKey: .`default`)
      try container.encodeIfPresent(self.items, forKey: .items)
      try container.encode(self.minItems, forKey: .minItems)
      try container.encode(self.maxItems, forKey: .maxItems)
      try container.encode(self.`enum`, forKey: .`enum`)
      try container.encode(self.properties, forKey: .properties)
      try container.encode(self.propertyOrdering, forKey: .propertyOrdering)
      try container.encode(self.`required`, forKey: .`required`)
      try container.encode(self.minProperties, forKey: .minProperties)
      try container.encode(self.maxProperties, forKey: .maxProperties)
      try container.encode(self.minimum, forKey: .minimum)
      try container.encode(self.maximum, forKey: .maximum)
      try container.encode(self.minLength, forKey: .minLength)
      try container.encode(self.maxLength, forKey: .maxLength)
      try container.encode(self.pattern, forKey: .pattern)
      try container.encodeIfPresent(self.example, forKey: .example)
      try container.encode(self.anyOf, forKey: .anyOf)
      try container.encodeIfPresent(self.additionalProperties, forKey: .additionalProperties)
      try container.encode(self.ref, forKey: .ref)
      try container.encode(self.defs, forKey: .defs)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.Schema"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
