// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if MigrationService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Request message for
  /// [MigrationService.SearchMigratableResources][google.cloud.aiplatform.v1.MigrationService.SearchMigratableResources].
  ///
  /// [google.cloud.aiplatform.v1.MigrationService.SearchMigratableResources]: <doc:MigrationServiceClient/searchMigratableResources(request:options:)>
  public struct SearchMigratableResourcesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The location that the migratable resources should be searched
    /// from. It's the Vertex AI location that the resources can be migrated to,
    /// not the resources' original location. Format:
    /// `projects/{project}/locations/{location}`
    public var parent: Swift.String = Swift.String()

    /// The standard page size.
    /// The default and maximum value is 100.
    public var pageSize: Swift.Int32 = Swift.Int32()

    /// The standard page token.
    public var pageToken: Swift.String = Swift.String()

    /// A filter for your search. You can use the following types of filters:
    ///
    /// *   Resource type filters. The following strings filter for a specific type
    ///     of [MigratableResource][google.cloud.aiplatform.v1.MigratableResource]:
    ///     *   `ml_engine_model_version:*`
    ///     *   `automl_model:*`
    ///     *   `automl_dataset:*`
    ///     *   `data_labeling_dataset:*`
    /// *   "Migrated or not" filters. The following strings filter for resources
    ///     that either have or have not already been migrated:
    ///     *   `last_migrate_time:*` filters for migrated resources.
    ///     *   `NOT last_migrate_time:*` filters for not yet migrated resources.
    ///
    /// [google.cloud.aiplatform.v1.MigratableResource]: <doc:MigratableResource>
    public var filter: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SearchMigratableResourcesRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SearchMigratableResourcesRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let parent = CodingKeys(stringValue: "parent")
      static let pageSize = CodingKeys(stringValue: "pageSize")
      static let pageToken = CodingKeys(stringValue: "pageToken")
      static let filter = CodingKeys(stringValue: "filter")

      static let _knownKeys: Set<Swift.String> = [
        "parent",
        "pageSize",
        "pageToken",
        "filter",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
        self.parent = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
        self.pageSize = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
        self.pageToken = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
        self.filter = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encode(self.pageSize, forKey: .pageSize)
      try container.encode(self.pageToken, forKey: .pageToken)
      try container.encode(self.filter, forKey: .filter)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.SearchMigratableResourcesRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
