// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TensorboardService
  public import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// One blob (e.g, image, graph) viewable on a blob metric plot.
  public struct TensorboardBlob: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. A URI safe key uniquely identifying a blob. Can be used to
    /// locate the blob stored in the Cloud Storage bucket of the consumer project.
    public var id: Swift.String = Swift.String()

    /// Optional. The bytes of the blob is not present unless it's returned by the
    /// ReadTensorboardBlobData endpoint.
    public var data: Foundation.Data = Foundation.Data()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TensorboardBlob`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TensorboardBlob().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let id = CodingKeys(stringValue: "id")
      static let data = CodingKeys(stringValue: "data")

      static let _knownKeys: Set<Swift.String> = [
        "id",
        "data",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .data) {
        self.data = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.data, forKey: .data)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `TensorboardBlob`: `"type.googleapis.com/google.cloud.aiplatform.v1.TensorboardBlob"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.TensorboardBlob"
    }

    /// Initialize an instance of `TensorboardBlob` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.TensorboardBlob"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `TensorboardBlob` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
