// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SessionService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Request message for
  /// [SessionService.UpdateSession][google.cloud.aiplatform.v1.SessionService.UpdateSession].
  ///
  /// [google.cloud.aiplatform.v1.SessionService.UpdateSession]: <doc:SessionServiceClient/updateSession(request:options:)>
  public struct UpdateSessionRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The session to update.
    /// Format:
    /// `projects/{project}/locations/{location}/reasoningEngines/{reasoning_engine}/sessions/{session}`
    public var session: Session? = nil

    /// Optional. Field mask is used to control which fields get updated. If the
    /// mask is not present, all fields will be updated.
    public var updateMask: GoogleWKT.WKTFieldMask? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UpdateSessionRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UpdateSessionRequest().with { $0.session = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let session = CodingKeys(stringValue: "session")
      static let updateMask = CodingKeys(stringValue: "updateMask")

      static let _knownKeys: Set<Swift.String> = [
        "session",
        "updateMask",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.session = try container.decodeIfPresent(Session.self, forKey: .session)
      self.updateMask = try container.decodeIfPresent(
        GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.session, forKey: .session)
      try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.UpdateSessionRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
