// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PipelineService || ScheduleService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Value is the value of the field.
  public struct Value: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var value: ValueOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Value`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Value().with { $0.intValue = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let intValue = CodingKeys(stringValue: "intValue")
      static let doubleValue = CodingKeys(stringValue: "doubleValue")
      static let stringValue = CodingKeys(stringValue: "stringValue")

      static let _knownKeys: Set<Swift.String> = [
        "intValue",
        "doubleValue",
        "stringValue",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var value: ValueOneOf? = nil
      let valueCheckAndSet = {
        if value != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'value'"))
        }
        value = $0
      }
      if let intValue = try container.decodeIfPresent(Swift.Int64.self, forKey: .intValue) {
        try valueCheckAndSet(.intValue(intValue))
      }
      if let doubleValue = try container.decodeIfPresent(Swift.Double.self, forKey: .doubleValue) {
        try valueCheckAndSet(.doubleValue(doubleValue))
      }
      if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
        try valueCheckAndSet(.stringValue(stringValue))
      }
      self.value = value
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.value {
        switch choice {
        case .intValue(let value):
          try container.encode(value, forKey: .intValue)
        case .doubleValue(let value):
          try container.encode(value, forKey: .doubleValue)
        case .stringValue(let value):
          try container.encode(value, forKey: .stringValue)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum ValueOneOf: Codable, Equatable, Sendable {
      /// An integer value.
      case intValue(Swift.Int64)
      /// A double value.
      case doubleValue(Swift.Double)
      /// A string value.
      case stringValue(Swift.String)
    }

    /// The type URL for `Value`: `"type.googleapis.com/google.cloud.aiplatform.v1.Value"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.Value"
    }

    /// Initialize an instance of `Value` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.aiplatform.v1.Value"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Value` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
