// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if VertexRagService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleCloudLocation
  @_spi(GoogleCloudInternal) public import GoogleIAMV1
  @_spi(GoogleCloudInternal) public import GoogleLongRunning
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// A service for retrieving relevant contexts.
  ///
  /// @Snippet(path: "VertexRagServiceQuickstart")
  public final class VertexRagServiceClient: Clients.VertexRagServiceProtocol, Sendable {
    let inner: any Clients.VertexRagServiceStub
    let pollingErrorPolicy: any GoogleGax.PollingErrorPolicy
    let pollingBackoffPolicy: any GoogleGax.PollingBackoffPolicy

    /// Creates a new `VertexRagServiceClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.VertexRagServiceStub = try Clients.VertexRagServiceTransport(options)
      inner = Clients.VertexRagServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.VertexRagServiceLogging(inner, logger: logger)
      }
      self.inner = inner
      self.pollingErrorPolicy = options.pollingErrorPolicy
      self.pollingBackoffPolicy = options.pollingBackoffPolicy
    }

    /// Retrieves relevant contexts for a query.
    ///
    /// @Snippet(path: "VertexRagService_RetrieveContexts")
    public func retrieveContexts(
      request: RetrieveContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.RetrieveContextsResponse {
      try await self.inner.retrieveContexts(request: request, options: options)
    }

    /// Given an input prompt, it returns augmented prompt from vertex rag store
    ///  to guide LLM towards generating grounded responses.
    ///
    /// @Snippet(path: "VertexRagService_AugmentPrompt")
    public func augmentPrompt(
      request: AugmentPromptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.AugmentPromptResponse {
      try await self.inner.augmentPrompt(request: request, options: options)
    }

    /// Given an input text, it returns a score that evaluates the factuality of
    /// the text. It also extracts and returns claims from the text and provides
    /// supporting facts.
    ///
    /// @Snippet(path: "VertexRagService_CorroborateContent")
    public func corroborateContent(
      request: CorroborateContentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.CorroborateContentResponse {
      try await self.inner.corroborateContent(request: request, options: options)
    }

    /// Agentic Retrieval Ask API for RAG.
    ///
    /// @Snippet(path: "VertexRagService_AskContexts")
    public func askContexts(
      request: AskContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.AskContextsResponse {
      try await self.inner.askContexts(request: request, options: options)
    }

    /// Asynchronous API to retrieves relevant contexts for a query.
    ///
    /// @Snippet(path: "VertexRagService_AsyncRetrieveContexts")
    public func asyncRetrieveContexts(
      request: AsyncRetrieveContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.asyncRetrieveContexts(request: request, options: options)
    }

    /// Asynchronous API to retrieves relevant contexts for a query.
    ///
    /// @Snippet(path: "VertexRagService_AsyncRetrieveContexts")
    public func asyncRetrieveContextsPollingUntilDone(
      request: AsyncRetrieveContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> AsyncRetrieveContextsResponse {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<AsyncRetrieveContextsResponse>.State in
        return try op._extractStatus(AsyncRetrieveContextsResponse.self)
      }
      let rawOp = try await self.asyncRetrieveContexts(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<AsyncRetrieveContextsResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
      return try await poller.wait()
    }

    /// Lists information about the supported locations for this service.
    ///
    /// @Snippet(path: "VertexRagService_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "VertexRagService_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Sets the access control policy on the specified resource. Replaces
    /// any existing policy.
    ///
    /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
    /// errors.
    ///
    /// @Snippet(path: "VertexRagService_SetIamPolicy")
    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self.inner.setIamPolicy(request: request, options: options)
    }

    /// Gets the access control policy for a resource. Returns an empty policy
    /// if the resource exists and does not have a policy set.
    ///
    /// @Snippet(path: "VertexRagService_GetIamPolicy")
    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self.inner.getIamPolicy(request: request, options: options)
    }

    /// Returns permissions that a caller has on the specified resource. If the
    /// resource does not exist, this will return an empty set of
    /// permissions, not a `NOT_FOUND` error.
    ///
    /// Note: This operation is designed to be used for building
    /// permission-aware UIs and command-line tools, not for authorization
    /// checking. This operation may "fail open" without warning.
    ///
    /// @Snippet(path: "VertexRagService_TestIamPermissions")
    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "VertexRagService_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "VertexRagService_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "VertexRagService_DeleteOperation")
    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "VertexRagService_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "VertexRagService_WaitOperation")
    public func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.waitOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `VertexRagServiceClient`.
    ///
    /// To mock `VertexRagServiceClient` change your functions to receive
    /// `some VertexRagServiceProtocol` or `any VertexRagServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol VertexRagServiceProtocol: Sendable {
      /// See `VertexRagServiceClient.retrieveContexts`.
      func retrieveContexts(
        request: RetrieveContextsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.RetrieveContextsResponse

      /// See `VertexRagServiceClient.augmentPrompt`.
      func augmentPrompt(
        request: AugmentPromptRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.AugmentPromptResponse

      /// See `VertexRagServiceClient.corroborateContent`.
      func corroborateContent(
        request: CorroborateContentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.CorroborateContentResponse

      /// See `VertexRagServiceClient.askContexts`.
      func askContexts(
        request: AskContextsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.AskContextsResponse

      /// See `VertexRagServiceClient.asyncRetrieveContexts`.
      func asyncRetrieveContexts(
        request: AsyncRetrieveContextsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `VertexRagServiceClient.asyncRetrieveContexts`.
      func asyncRetrieveContextsPollingUntilDone(
        request: AsyncRetrieveContextsRequest, options: GoogleGax.RequestOptions
      ) async throws -> AsyncRetrieveContextsResponse

      /// See `VertexRagServiceClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `VertexRagServiceClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `VertexRagServiceClient.setIamPolicy`.
      func setIamPolicy(
        request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      /// See `VertexRagServiceClient.getIamPolicy`.
      func getIamPolicy(
        request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      /// See `VertexRagServiceClient.testIamPermissions`.
      func testIamPermissions(
        request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

      /// See `VertexRagServiceClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `VertexRagServiceClient.deleteOperation`.
      func deleteOperation(
        request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `VertexRagServiceClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `VertexRagServiceClient.waitOperation`.
      func waitOperation(
        request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation
    }
  }

  // Default implementations
  extension Clients.VertexRagServiceProtocol {
    public func retrieveContexts(request: RetrieveContextsRequest) async throws
      -> GoogleCloudAIPlatformV1.RetrieveContextsResponse
    {
      try await self.retrieveContexts(request: request, options: .init())
    }

    public func retrieveContexts(
      request: RetrieveContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.RetrieveContextsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func retrieveContexts(
      parent: Swift.String,
      query: RagQuery?,
    ) async throws -> GoogleCloudAIPlatformV1.RetrieveContextsResponse {
      let request = RetrieveContextsRequest().with {
        $0.parent = parent
        $0.query = query
      }
      return try await self.retrieveContexts(request: request)
    }

    public func augmentPrompt(request: AugmentPromptRequest) async throws
      -> GoogleCloudAIPlatformV1.AugmentPromptResponse
    {
      try await self.augmentPrompt(request: request, options: .init())
    }

    public func augmentPrompt(
      request: AugmentPromptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.AugmentPromptResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func augmentPrompt(
      parent: Swift.String,
      model: AugmentPromptRequest.Model?,
      vertexRagStore: GoogleCloudAIPlatformV1.VertexRagStore,
    ) async throws -> GoogleCloudAIPlatformV1.AugmentPromptResponse {
      let request = AugmentPromptRequest().with {
        $0.parent = parent
        $0.model = model
        $0.dataSource = .vertexRagStore(vertexRagStore)
      }
      return try await self.augmentPrompt(request: request)
    }

    public func corroborateContent(request: CorroborateContentRequest) async throws
      -> GoogleCloudAIPlatformV1.CorroborateContentResponse
    {
      try await self.corroborateContent(request: request, options: .init())
    }

    public func corroborateContent(
      request: CorroborateContentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.CorroborateContentResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func corroborateContent(
      parent: Swift.String,
      content: Content?,
      facts: [Fact],
    ) async throws -> GoogleCloudAIPlatformV1.CorroborateContentResponse {
      let request = CorroborateContentRequest().with {
        $0.parent = parent
        $0.content = content
        $0.facts = facts
      }
      return try await self.corroborateContent(request: request)
    }

    public func askContexts(request: AskContextsRequest) async throws
      -> GoogleCloudAIPlatformV1.AskContextsResponse
    {
      try await self.askContexts(request: request, options: .init())
    }

    public func askContexts(
      request: AskContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAIPlatformV1.AskContextsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func askContexts(
      parent: Swift.String,
      query: RagQuery?,
    ) async throws -> GoogleCloudAIPlatformV1.AskContextsResponse {
      let request = AskContextsRequest().with {
        $0.parent = parent
        $0.query = query
      }
      return try await self.askContexts(request: request)
    }

    public func asyncRetrieveContexts(request: AsyncRetrieveContextsRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.asyncRetrieveContexts(request: request, options: .init())
    }

    public func asyncRetrieveContexts(
      request: AsyncRetrieveContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func asyncRetrieveContextsPollingUntilDone(request: AsyncRetrieveContextsRequest)
      async throws -> AsyncRetrieveContextsResponse
    {
      return try await self.asyncRetrieveContextsPollingUntilDone(
        request: request, options: .init())
    }

    public func asyncRetrieveContextsPollingUntilDone(
      request: AsyncRetrieveContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> AsyncRetrieveContextsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func asyncRetrieveContextsPollingUntilDone(
      parent: Swift.String,
      query: RagQuery?,
    ) async throws -> AsyncRetrieveContextsResponse {
      let request = AsyncRetrieveContextsRequest().with {
        $0.parent = parent
        $0.query = query
      }
      return try await self.asyncRetrieveContextsPollingUntilDone(request: request)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest
    ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
      self.listLocationsByItems(request: request, options: .init())
    }

    /// Lists information about the supported locations for this service.
    ///
    /// @Snippet(path: "VertexRagService_ListLocations")
    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
      -> GoogleIAMV1.Policy
    {
      try await self.setIamPolicy(request: request, options: .init())
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
      -> GoogleIAMV1.Policy
    {
      try await self.getIamPolicy(request: request, options: .init())
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse
    {
      try await self.testIamPermissions(request: request, options: .init())
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest
    ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
      self.listOperationsByItems(request: request, options: .init())
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "VertexRagService_ListOperations")
    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listOperationsByItems(
      name: Swift.String,
      filter: Swift.String,
    ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return self.listOperationsByItems(request: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
      try await self.deleteOperation(request: request, options: .init())
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.DeleteOperationRequest().with {
        $0.name = name
      }
      try await self.deleteOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }

    public func waitOperation(request: GoogleLongRunning.WaitOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.waitOperation(request: request, options: .init())
    }

    public func waitOperation(
      request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'VertexRagService' trait in Package.swift to use this client."
  )
  public final class VertexRagServiceClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'VertexRagService' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
